---
title: "mask"
output: html_document
---

### **Component: Mask Prediction**

**ORIENTATION**

The goal of masking range maps (or species distribution models) is to improve spatial (and possibly temporal) accuracy of species’ range estimates by incorporating different types of information. Specifically, masking can include various forms of post-processing of SDMs to improve the estimation of currently occupied locations. Often, statistically-based SDMs are used to identify suitable environmental conditions, as the models detect locations with similar environmental conditions to where the species was observed. These modeled maps are best interpreted as potential distributions since other processes besides abiotic conditions may restrict the distribution, such as dispersal, biotic interactions, social dynamics, historical contingencies, or human modification of habitat. In contrast, realized distributions describe those locations that are actually occupied by the species (at some spatial resolution) and may be smaller than potential distributions (Soberón 2007). By starting with potential distributions from any form of SDM, we can use other pieces of information to refine these models to approach realized distributions.

Information derived from expert knowledge is often useful for determining unsuitable and unoccupied locations, and thus can help refine estimates (Velásquez-Tibatá et al. 2019). Importantly, relevant expert knowledge is typically related to non-climatic factors, making it complementary to SDMs commonly fit with climatic variables. Beginning with an expert-drawn map or SDM, we can use different approaches or a series of filters to refine estimates of realized distributions based on expert knowledge (Merow et al. 2022), enabling downstream calculation of range sizes and other useful metrics of biodiversity and its change (**Component: Calculate Indicators**).

Here, the **Mask Prediction** component implements various methods for estimating realized distributions based on different types of data, with functions from the R package `maskRangeR` (Merow et al. 2022). Additional information not included as a predictor in an SDM can be described by masks that differentiate potential habitat from non-habitat. 

`wallace` currently allows users to: 1) upload a user prediction such as an SDM for use in other modules in this component or downstream components (Module *Upload User Prediction*), 2) mask a prediction with a user-specified shapefile (Module *Mask by Shapefile*), 3) add or remove areas of a prediction using expert-defined areas by drawing or uploading a user-specified polygon via shapefile or CSV (Module *Mask by Drawn Polygon*), 4) mask a prediction by determining an appropriate value threshold for the mask through a temporal matching approach with dated occurrence and environmental rasters (Module *Temporal Extract*).

---

**ORIENTACIÓN**

El objetivo de enmascarar los mapas de distribución (o modelos de distribución de especies, SDM) es mejorar la precisión espacial (y posiblemente temporal) de las estimaciones de distribución de especies mediante la incorporación de diferentes tipos de información. Específicamente, el enmascaramiento puede incluir varias formas de posprocesamiento de SDM para mejorar la estimación de las ubicaciones actualmente ocupadas. A menudo, los SDM basados en estadísticas se utilizan para identificar las condiciones ambientales adecuadas, ya que los modelos detectan ubicaciones con condiciones ambientales similares a las de donde se observó la especie. Estos mapas modelados se interpretan mejor como distribuciones potenciales, ya que otros procesos además de las condiciones abióticas pueden restringir la distribución, como la dispersión, las interacciones bióticas, la dinámica social, las contingencias históricas o la modificación humana del hábitat. Por el contrario, las distribuciones realizadas describen aquellas ubicaciones que en realidad están ocupadas por la especie (con alguna resolución espacial) y pueden ser más pequeñas que las distribuciones potenciales (Soberón 2007). Al comenzar con distribuciones potenciales de cualquier forma de SDM, podemos usar otras piezas de información para refinar estos modelos para aproximarnos a las distribuciones realizadas.

La información derivada del conocimiento de expertos a menudo es útil para determinar ubicaciones inadecuadas y desocupadas y, por lo tanto, puede ayudar a refinar las estimaciones (Velásquez-Tibatá et al. 2019). Es importante destacar que el conocimiento experto relevante generalmente está relacionado con factores no climáticos, lo que lo hace complementario a los SDM que comúnmente se ajustan a las variables climáticas. Comenzando con un mapa elaborado por expertos o SDM, podemos usar diferentes enfoques o una serie de filtros para refinar las estimaciones de distribuciones realizadas basadas en el conocimiento experto (Merow et al. 2022), lo que permite el cálculo posterior de los tamaños de rango y otras métricas útiles de biodiversidad y su cambio (**Componente: Calcular Indicadores**).

Aquí, el componente **Mask Prediction** implementa varios métodos para estimar las distribuciones realizadas en función de diferentes tipos de datos, con funciones del paquete R `maskRangeR` (Merow et al. 2022). La información adicional no incluida como predictor en un SDM se puede describir mediante máscaras que diferencian el hábitat potencial del no hábitat.

Wallace actualmente permite a los usuarios: 1) cargar una predicción de usuario como un SDM para usar en otros módulos en este componente o componentes posteriores (Módulo *Upload User Prediction*), 2) enmascarar una predicción con un shapefile especificado por el usuario (Módulo *Mask by Shapefile*), 3) agregar o eliminar áreas de una predicción usando áreas definidas por expertos dibujando o cargando un polígono especificado por el usuario a través de un archivo shapefile o CSV (Módulo *Mask by Drawn Polygon*), 4) enmascarar una predicción determinando un umbral de valor apropiado para el máscara a través de un enfoque de coincidencia temporal con ocurrencia fechada y rásteres ambientales (Módulo *Temporal Extract*).

---

**REFERENCES**

Merow, C., Galante, P.J., Kass, J.M., Aiello-Lammens, M., Babich Morrow, C., Gerstner, B.E., Grisales-Betancur, V., Moore, A., Noguera-Urbano, E.A., Pinilla- Buitrago, G.E., Velasquez-Tibatá, J., Anderson, R.P., Blair, M.E. (2022). Operationalizing expert knowledge in species' range estimates using diverse data types. *Frontiers of Biogeography*, 14(2), e53589. <a href="https://doi.org/10.21425/F5FBG53589" target="_blank">DOI:10.21425/F5FBG53589</a>

Soberón, J. (2007). Grinnellian and Eltonian niches and geographic distributions of species. *Ecology Letters*, 10, 1115–1123. <a href="https://doi.org/10.1111/j.1461-0248.2007.01107.x" target="_blank">DOI:10.1111/j.1461-0248.2007.01107.x</a>

Velásquez-Tibatá, J., Olaya-Rodríguez, M.H., López-Lozano, D., Gutiérrez, C., González, I. & Londoño-Murcia, M.C. (2019). BioModelos: A collaborative online system to map species distributions. *PloS ONE* 14(3), e0214522. <a href="https://doi.org/10.1371/journal.pone.0214522" target="_blank">DOI:10.1371/journal.pone.0214522</a>
