```{asis, echo = {{removeByID_knit}}, eval = {{removeByID_knit}}, include = {{removeByID_knit}}}
Remove the occurrence localities by ID.
```

```{r, echo = {{removeByID_knit}}, include = {{removeByID_knit}}}
# remove the rows that match the occIDs selected
occs.{{sp}} <- c2_removeByID(occs.{{sp}}, {{removeByID_id}})
```

```{asis, echo = {{selectByID_knit}}, eval = {{selectByID_knit}}, include = {{selectByID_knit}}}
The following code recreates the polygon used to select occurrences to keep in the analysis.
```

```{r, echo = {{selectByID_knit}}, include = {{selectByID_knit}}}
occs.{{sp}} <- c2_selectOccs(occs.{{sp}}, "{{selectByID_xy}}", "{{selectByID_id}}")
```

``` {asis, echo = {{worldclim_knit}}, eval = {{worldclim_knit}}, include = {{worldclim_knit}}}
Using WorldClim (http://www.worldclim.org/) bioclimatic dataset at resolution of `r {{wcRes}}` arcmin.
```

```{r, echo = {{worldclim_knit}}, include = {{worldclim_knit}}}
envs.{{sp}} <- c3_worldclim({{wcRes}}, {{bcSel}}, {{mapCntr}}, {{wcBrick}})
occs.{{sp}}.xy <- occs.{{sp}}[c('longitude', 'latitude')]
occs.{{sp}}.vals <- as.data.frame(raster::extract(envs.{{sp}}, occs.{{sp}}.xy))
# remove occurrence records with NA environmental values
occs.{{sp}} <- remEnvsValsNA(occs.{{sp}}, occs.{{sp}}.vals)
# also remove variable value rows with NA environmental values
occs.{{sp}}.vals <- na.omit(occs.{{sp}}.vals)
# add columns for env variable values for each occurrence record
occs.{{sp}} <- cbind(occs.{{sp}}, occs.{{sp}}.vals)
```

```{asis, echo = {{bgExtent_knit}}, eval = {{bgExtent_knit}}, include = {{bgExtent_knit}}}
### Process Environmental Data
Background selection technique chosen as "`r '{{bgSel}}'`".
```

```{r, echo = {{bgExtent_knit}}, include = {{bgExtent_knit}}}
bgExt.{{sp}} <- c4_bgExtent(occs.{{sp}}, "{{bgSel}}", {{bgBuf}})
```

```{asis, echo = {{bgMskSamplePts_knit}}, eval = {{bgMskSamplePts_knit}}, include = {{bgMskSamplePts_knit}}}
### Process Environmental Data
Environmental rasters masked to background extent, and *n* = `r {{bgPtsNum}}` background points sampled over this extent.
```

```{r, echo = {{bgMskSamplePts_knit}}, include = {{bgMskSamplePts_knit}}}
bgMask.{{sp}} <- c4_bgMask(occs.{{sp}}, envs.{{sp}}, bgExt.{{sp}})

bg.{{sp}} <- c4_bgSample(occs.{{sp}}, bgMask.{{sp}}, {{bgPtsNum}})
bg.{{sp}}.vals <- as.data.frame(raster::extract(bgMask.{{sp}}, bg.{{sp}}))
```

```{asis, echo = {{espace_pca_knit}}, eval = {{espace_pca_knit}}, include = {{espace_pca_knit}}}
### Environmental Space Analyses
Environmental PCA run.
```

```{r, echo = {{espace_pca_knit}}, include = {{espace_pca_knit}}}
pca.sel <- {{pcaSel}}
pca.{{sp}} <- cESpace_pca("{{espace.sp1}}", "{{espace.sp2}}",
                          occs.{{espace.sp1}}.vals[pca.sel],
                          occs.{{espace.sp2}}.vals[pca.sel],
                          bg.{{espace.sp1}}.vals[pca.sel],
                          bg.{{espace.sp2}}.vals[pca.sel])
```

```{asis, echo = {{espace_occDens_knit}}, eval = {{espace_occDens_knit}}, include = {{espace_occDens_knit}}}
### Environmental Space Analyses
Occurrence density run.
```

```{r, echo = {{espace_occDens_knit}}, include = {{espace_occDens_knit}}}
occDens.{{sp}} <- cESpace_occDens("{{espace.sp1}}", "{{espace.sp2}}", pca.{{sp}})
```

```{asis, echo = {{espace_nicheOv_knit}}, eval = {{espace_nicheOv_knit}}, include = {{espace_nicheOv_knit}}}
### Environmental Space Analyses
Niche overlap run.
```

```{r, echo = {{espace_nicheOv_knit}}, include = {{espace_nicheOv_knit}}}
nicheOv.{{sp}} <- cESpace_nicheOv(occDens.{{sp}}[["{{espace.sp1}}"]],
                                  occDens.{{sp}}[["{{espace.sp2}}"]], pca.{{sp}})
```
