if (!require("shiny"))
  install.packages("shiny")
if (!require("devtools"))
  install.packages("devtools")
if (!require('shinyapps')) devtools::install_github("rstudio/shinyapps")
if (!require('leaflet')) devtools::install_github("rstudio/leaflet")
if (!require("DT")) devtools::install_github("rstudio/DT")

library(shiny)
library(shinyapps)
library(leaflet)
library(DT)

# function to make two small input boxes next to each other
# textInputRow<-function (inputId, label, value = "")
# {
#   div(style="display:inline-block",
#       tags$label(label, `for` = inputId),
#       tags$input(id = inputId, type = "text", value = value,class="input-small"))
# }

title <- HTML('<span style="font-size:25pt">WALLACE beta v0.1:</span>
              <span style="font-size:15pt">Harnessing Digital Biodiversity Data for Predictive Modeling, fueled by R</span><br>
              <span style="font-size:10pt">Developers: Jamie M. Kass, Matthew Aiello-Lammens, Bruno Vilela, Robert Muscarella, Robert P. Anderson</span><br><br>')

# Define UI for application
shinyUI(pageWithSidebar(title,
                        sidebarPanel(includeCSS("styles.css"),
                                     includeScript("scroll.js"),
                                     conditionalPanel("input.tabs == 0",
                                                      includeMarkdown("www/tab0content.Rmd")
                                     ),
                                     conditionalPanel("input.tabs == 1",
                                                      h4("Obtain Occurrence Data"),
                                                      radioButtons("dbSelect", "Modules Available:",
                                                                   choices = list("GBIF", "eBird (not functional)", "User-specified" = 'user'),
                                                                   selected = ''),
                                                      HTML('<hr>'),
                                                      conditionalPanel("input.dbSelect == 'GBIF'",
                                                                       div('Module: GBIF', id="mod"),
                                                                       span('via', id="pkgDes"),
                                                                       span('rgbif', id="rpkg"),
                                                                       span('package: Interface to the Global Biodiversity Information Facility API', id="pkgDes"),
                                                                       br(), br(),
                                                                       textInput("gbifName", label = "Enter scientific name of species (format: genus species)", value = 'tremarctos ornatus'),
                                                                       actionButton("goName", "Search GBIF"),
                                                                       br(), br(),
                                                                       sliderInput("occurrences", "Maximum number of occurrences:", min = 1, max = 500, value = 20),
                                                                       br(),
                                                                       downloadButton('downloadGBIFcsv', "Download Occurrence CSV"),
                                                                       HTML('<hr>')
                                                      ),
                                                      conditionalPanel("input.dbSelect == 'user'",
                                                                       fileInput("userCSV", label = "Upload Occurrence CSV")),
                                                      includeMarkdown("www/tab1content.Rmd"),
                                                      conditionalPanel("input.dbSelect == 'GBIF'",
                                                                       span("rgbif", id = "rpkg"), "references", br(),
                                                                       div('Developers: Scott Chamberlain, Karthik Ram, Vijay Barve, Dan Mcglinn', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/rgbif/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("documentation", href = "http://www.gbif.org/resource/81747", target = "_blank")
                                                      )
                                     ),
                                     conditionalPanel("input.tabs == 2",
                                                      h4("Process Occurrence Data"),
                                                      radioButtons("procOccSelect", "Modules Available:",
                                                                   choices = list("Select Localities" = 'selpts',
                                                                                  "Spatial Thin" = 'spthin',
                                                                                  "Environmental Thin (not functional)"),
                                                                   selected = ''),
                                                      HTML('<hr>'),
                                                      conditionalPanel("input.procOccSelect == 'selpts'",
                                                                       'In this module, only selected points are used in proceeding analyses.
                                                                       Click on the map to draw a polygon, then press "Select Points" to select
                                                                       the overlapping points. You can then draw another polygon and select other
                                                                       points, and repeat this process until all the points you want to include in
                                                                       the analysis are selected. If you want to reset, just press "Erase Polygons".',
                                                                       HTML('<hr>')),
                                                      conditionalPanel("input.procOccSelect == 'spthin'",
                                                                       div('Module: Spatial Thin', id="mod"),
                                                                       span('via', id="pkgDes"),
                                                                       span('spThin', id="rpkg"),
                                                                       span('package: Spatial Thinning of Species Occurrence Records', id="pkgDes"),
                                                                       br(), br(),
                                                                       numericInput("thinDist", label = "Thinning distance (km)", value = 0),
                                                                       actionButton("goThin", "Run spThin"),
                                                                       br(), br(),
                                                                       downloadButton('downloadThincsv', "Download Occurrence CSV")
                                                      ),
                                                      includeMarkdown("www/tab2content.Rmd"),
                                                      conditionalPanel("input.procOccSelect == 'spatial thin'",
                                                                       span("spThin", id = "rpkg"), "references", br(),
                                                                       div('Developers:  Matthew E. Aiello-Lammens, Rob A. Boria, Alex Radosavljevic, Bruno Vilela,
                                                                           Robert P. Anderson', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/spThin/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/ecog.01132/abstract", target = "_blank")
                                                                       )
                                     ),
                                     conditionalPanel("input.tabs == 3",
                                                      h4("Obtain Environmental Data"),
                                                      radioButtons("envSelect", "Modules Available:",
                                                                   choices = list("WorldClim", "Climond (not functional)" = 'Climond', "PRISM (not functional)" = "PRISM",
                                                                                  "MARSPEC (not functional)" = "MARSPEC", "User-specified (not functional)"),
                                                                   selected = ''),
                                                      HTML('<hr>'),
                                                      conditionalPanel("input.envSelect == 'WorldClim'",
                                                                       div('Module: Worldclim', id="mod"),
                                                                       span('via', id="pkgDes"),
                                                                       span('dismo', id="rpkg"),
                                                                       span('package: Species Distribution Modeling', id="pkgDes"),
                                                                       br(), br(),
                                                                       selectInput("pred", label = "Choose environmental data resolution",
                                                                                   choices = list("Choose resolution" = "",
                                                                                                  "2.5 arcmin WorldClim bio1-19" = 2.5,
                                                                                                  "5 arcmin WorldClim bio1-19" = 5,
                                                                                                  "10 arcmin WorldClim bio1-19" = 10,
                                                                                                  "User input (not functional)" = 'user')),
                                                                       #"Upload from Dropbox" = 'db'))
                                                                       HTML('<hr>')
                                                      ),
                                                      conditionalPanel("input.envSelect == 'Climond'",
                                                                       a("Climond website", href = "https://www.climond.org/", target = "_blank"), HTML('<hr>')),
                                                      conditionalPanel("input.envSelect == 'MARSPEC'",
                                                                       a("MARSPEC website", href = "http://www.marspec.org/Home.html", target = "_blank"), HTML('<hr>')),
                                                      conditionalPanel("input.envSelect == 'PRISM'",
                                                                       a("PRISM website", href = "http://www.prism.oregonstate.edu/", target = "_blank"), HTML('<hr>')),
                                                      includeMarkdown("www/tab3content.Rmd"),
                                                      conditionalPanel("input.envSelect == 'WorldClim'",
                                                                       span("dismo", id = "rpkg"), "references", br(),
                                                                       div('Developers:  Robert J. Hijmans, Steven Phillips, John Leathwick, Jane Elith', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/dismo/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("documentation", href="https://cran.r-project.org/web/packages/dismo/dismo.pdf", target = "_blank"),
                                                                       " | ",
                                                                       a("Worldclim", href="http://worldclim.org", target="_blank")
                                                      )
                                                      #                                                       conditionalPanel("input.pred == 'db'",
                                                      #                                                                        textInput("dbAscFname", "File name"),
                                                      #                                                                        textInput("dbAscKey", "Dropbox Key"),
                                                      #                                                                        textInput("dbAscCRS", "Coordinate System",value='+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0'),
                                                      #                                                                        textInput("dbAscDims", "Dimensions"))
                                     ),
                                     conditionalPanel("input.tabs == 4",
                                                      h4("Process Environmental Data"),
                                                      radioButtons("envProcSelect", "Modules Available:",
                                                                   choices = list("Select Background Extent" = "backg",
                                                                                  "Change Resolution (not functional)"),
                                                                   selected = ''),

                                                      HTML('<hr>'),
                                                      conditionalPanel("input.envProcSelect == 'backg'",
                                                                       div('Module: Select Background Extent', id="mod"),
                                                                       span('via', id="pkgDes"),
                                                                       span('sp', id="rpkg"),
                                                                       span('and', id="pkgDes"),
                                                                       span('rgeos', id="rpkg"),
                                                                       span('packages: Title Classes and Methods for Spatial Data |
                                                                            Interface to Geometry Engine - Open Source (GEOS)', id="pkgDes"),
                                                                       br(), br(),
                                                                       radioButtons("backgSelect", "Background Extents:",
                                                                                    choices = list("Bounding box" = 'bb', "Minimum convex polygon" = 'mcp',
                                                                                                   "User-specified shapefile" = 'user'),
                                                                                    selected = '')
                                                                       ),
                                                      conditionalPanel("input.backgSelect == 'user'",
                                                                       #  shinyFilesButton('userBackg', label='Upload Shapefile', title='Please select a file', multiple=TRUE)),
                                                                       fileInput("userBackg", label = "Upload Shapefile",
                                                                                 accept=c('.shp','.dbf','.sbn','.sbx','.shx',".prj", ".csv"), multiple=TRUE)),
                                                      conditionalPanel("input.envProcSelect == 'backg'",
                                                                       numericInput("backgBuf", label = "Study region buffer distance (degree)", value = 0),
                                                                       actionButton("goBackgMask", "Mask Predictors by Background"), br(), br(),
                                                                       selectInput('mskPredsFileType', label = "Select File Type",
                                                                                   choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff')),
                                                                       downloadButton('downloadMskPreds', "Download Masked Predictors"),
                                                                       HTML('<hr>')),
                                                      includeMarkdown("www/tab4content.Rmd"),
                                                      conditionalPanel("input.backgSelect == 'bb' || input.backgSelect == 'mcp'",
                                                                       span("sp", id = "rpkg"), "references", br(),
                                                                       div('Developers:  Edzer Pebesma, Roger Bivand, Barry Rowlingson, Virgilio Gomez-Rubio,
                                                                           Robert Hijmans, Michael Sumner, Don MacQueen, Jim Lemon, Josh O\'Brien', id="pkgDes"), br(),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/sp/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("documentation", href="https://cran.r-project.org/web/packages/sp/sp.pdf", target = "_blank"),
                                                                       span("rgeos", id = "rpkg"), "references", br(),
                                                                       div('rgeos Developers:  Roger Bivand, Colin Rundel, Edzer Pebesma, Karl Ove Hufthammer', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/rgeos/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("documentation", href="https://cran.r-project.org/web/packages/rgeos/rgeos.pdf", target = "_blank")
                                                      )

                                     ),
                                     conditionalPanel("input.tabs == 5",
                                                      h4("Partition Occurrence Data"),
                                                      radioButtons("partSelect", "Modules Available:",
                                                                   choices = list("Spatial Partition" = 'sp',
                                                                                  "Non-spatial Partition" = 'nsp',
                                                                                  "User-specified (not functional)"),
                                                                   selected = ''),
                                                      HTML('<hr>'),
                                                      conditionalPanel("input.partSelect == 'sp'",
                                                                       div('Module: Spatial Partition', id="mod")),
                                                      conditionalPanel("input.partSelect == 'nsp'",
                                                                       div('Module: Non-Spatial Partition', id="mod")),

                                                      conditionalPanel("input.partSelect == 'sp' || input.partSelect == 'nsp'",
                                                                       radioButtons("partSelect2", "Modules Available:",
                                                                                    choices = list("Choose"), selected = ''),
                                                                       span('via', id="pkgDes"),
                                                                       span('ENMeval', id="rpkg"),
                                                                       span('package: Automated Runs and Evaluations of Ecological Niche Models', id="pkgDes")),
                                                      conditionalPanel("input.partSelect == 'sp' & (input.partSelect2 == 'cb1' | input.partSelect2 == 'cb2')",
                                                                       numericInput("aggFact", label = "Aggregation Factor", value = 2, min = 2)),
                                                      conditionalPanel("input.partSelect2 == 'random'",
                                                                       numericInput("kfolds", label = "Number of Folds", value = 2, min = 2)),
#                                                       conditionalPanel("input.partSelect == 'user'",
#                                                                        br(), br(),
#                                                                        uiOutput('occgrpSel'),
#                                                                        uiOutput('bggrpSel')),
                                                      conditionalPanel("input.partSelect == 'sp' || input.partSelect == 'nsp'",
                                                                       br(), actionButton("goPart", "Partition"), br(), br(),
                                                                       downloadButton('downloadPart', "Download Partitioned Occurrence CSV"),
                                                                       HTML('<hr>')),
                                                      includeMarkdown("www/tab5content.Rmd"),
                                                      conditionalPanel("input.partSelect == 'sp' || input.partSelect == 'nsp'",
                                                                       span("ENMeval", id = "rpkg"), "references", br(),
                                                                       div('Developers:  Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                                           Jamie M. Kass, Maria Uriarte, Robert P. Anderson', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/ENMeval/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank")
                                                                       )
                                     ),
                                     conditionalPanel("input.tabs == 6",
                                                      h4("Build and Evaluate Niche Model"),
                                                      radioButtons("modSelect", "Modules Available:",
                                                                   choices = list("Bioclim", "Maxent", "GAM (not functional)",
                                                                                  "Boosted Regression Trees (not functional)"),
                                                                   selected = ''),
                                                      HTML('<hr>'),
                                                      conditionalPanel("input.modSelect == 'Maxent'",
                                                                       div('Module: Maxent', id="mod")),
                                                      conditionalPanel("input.modSelect == 'Bioclim'",
                                                                       div('Module: Bioclim', id="mod")),
                                                      conditionalPanel("input.modSelect != null",
                                                                       span('via', id="pkgDes"),
                                                                       span('ENMeval', id="rpkg"),
                                                                       span('package: Automated Runs and Evaluations of Ecological Niche Models', id="pkgDes")),
                                                      conditionalPanel("input.modSelect == 'Bioclim'",
                                                                       "BIOCLIM STUFF",
                                                                       conditionalPanel("input.bcTabs == 2",
                                                                                        numericInput("bc1", "Axis 1", value = 1, min = 1, max = 19),
                                                                                        numericInput("bc2", "Axis 2", value = 2, min = 1, max = 19),
                                                                                        selectInput('bcProb', label = "Set threshold",
                                                                                                    choices = list("90%" = 0.9, "95%" = 0.95, "100%" = 1),
                                                                                                    selected = 0.9)
                                                                       )
                                                      ),
                                                      conditionalPanel("input.modSelect == 'Maxent'",
                                                                       checkboxGroupInput("fcs", label = "Select feature classes (flexibility of modeled response)",
                                                                                          choices = list("L" = "L", "LQ" = "LQ", "H" = "H",
                                                                                                         "LQH" = "LQH", "LQHP" = "LQHP", "LQHPT" = "LQHPT")),
                                                                       sliderInput("rms", label = "Select regularization multipliers (penalty against complexity)",
                                                                                   min = 0, max = 10, value = c(1, 5)),
                                                                       numericInput("rmsBy", label = "RM step value", value = 1)
                                                      ),
                                                      conditionalPanel("input.modSelect != null",
                                                                       actionButton("goEval", "Build & Evaluate Models"), br(), br(),
                                                                       downloadButton('downloadEvalcsv', "Download Results CSV"), br(), br(),
                                                                       downloadButton('downloadEvalPlots', "Download Plots PNG"),
                                                                       HTML('<hr>')),
                                                      includeMarkdown("www/tab6content.Rmd"),
                                                      conditionalPanel("input.modSelect != null",
                                                                       span("ENMeval", id = "rpkg"), "references", br(),
                                                                       div('Developers:  Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                                           Jamie M. Kass, Maria Uriarte, Robert P. Anderson', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/ENMeval/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank")
                                                                       )
                                     ),
                                     conditionalPanel("input.tabs == 7",
                                                      h4("Visualize Model Results"),
                                                      radioButtons("visSelect", "Modules Available:",
                                                                   choices = list("Map Prediction" = 'map', "Response Curves (not functional)"),
                                                                   selected = ''),
                                                      HTML('<hr>'),
                                                      conditionalPanel("input.visSelect == 'map'",
                                                                       div('Module: Map Prediction', id="mod"),
                                                                       span('via', id="pkgDes"),
                                                                       span('raster', id="rpkg"),
                                                                       span('package: Geographic Data Analysis and Modeling', id="pkgDes"),
                                                                       br(), br(),
                                                                       uiOutput("predSel"),
                                                                       selectInput('predForm', label = "Prediction output",
                                                                                   choices = list("Choose output" = "", "raw" = 1, "logistic" = 2)),
                                                                       selectInput('predThresh', label = "Set threshold",
                                                                                   choices = list("No threshold" = 'raw',
                                                                                                  "MTP" = 'mtp', "10%" = 'p10'),
                                                                                   selected = ''),
                                                                       br(),
                                                                       actionButton("plotPred", "Plot Prediction"),
                                                                       br(), br(),
                                                                       selectInput('predFileType', label = "Select File Type",
                                                                                   choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff',
                                                                                                  "PNG" = "png")),
                                                                       downloadButton('downloadPred', "Download Current Prediction"),
                                                                       HTML('<hr>')
                                                      ),
                                                      includeMarkdown("www/tab7content.Rmd"),
                                                      conditionalPanel("input.visSelect == 'map'",
                                                                       span("raster", id = "rpkg"), "references", br(),
                                                                       div('Developers:  Robert J. Hijmans, Jacob van Etten, Joe Cheng, Matteo Mattiuzzi,
                                                                           Michael Sumner, Jonathan A. Greenberg, Oscar Perpinan Lamigueiro, Andrew Bevan,
                                                                           Etienne B. Racine, Ashton Shortridge', id="pkgDes"),
                                                                       a("CRAN", href = "http://cran.r-project.org/web/packages/raster/index.html", target = "_blank"),
                                                                       " | ",
                                                                       a("documentation", href="https://cran.r-project.org/web/packages/raster/raster.pdf", target = "_blank")
                                                                       ),
                                                      HTML('<hr>'),
                                                      selectInput('mdType', label = "R Markdown Download Type",
                                                                  choices = list("Rmd", "PDF")),
                                                      downloadButton('downloadMD', 'Download History in R Markdown'),
                                                      includeMarkdown("www/downloadmarkdown.Rmd")
                                                      ),
                                     conditionalPanel("input.tabs == 8",
                                                      h4("About")
                                     )
                        ),
                        mainPanel(
                          tabsetPanel(id = "tabs",
                                      tabPanel("Introduction", value=0),
                                      tabPanel("1) Obtain Occ Data", value=1),
                                      tabPanel("2) Process Occ Data", value=2),
                                      tabPanel("3) Obtain Env Data", value=3),
                                      tabPanel("4) Process Env Data", value=4),
                                      tabPanel("5) Partition Occ Data", value=5),
                                      tabPanel("6) Build Niche Model", value=6),
                                      tabPanel("7) Visualize Prediction", value=7),
                                      tabPanel("About", value=8)
                          ),
                          fluidRow(
                            column(9,
                                   conditionalPanel("input.tabs != 0 && input.tabs != 8",
                                                    "LOG",
                                                    div(id = "wallaceLog", class = "scrollbox", htmlOutput("log")))
                            ),
                            column(3,
                                   conditionalPanel("input.tabs == 2 && input.procOccSelect == 'selpts'", actionButton("erasePoly", "Erase Polygons"), br(), br(),
                                                    actionButton("selectPoly", "Select Points"))
                            )
                          ),
                          br(),
                          conditionalPanel("input.tabs != 6 && input.tabs != 8", leafletOutput("map", height=600)),
                          br(),
                          conditionalPanel("input.tabs != 0 && input.tabs != 6 && input.tabs != 8", DT::dataTableOutput('occTbl')),
                          conditionalPanel("input.tabs == 6", uiOutput('evalTabs')),
                          conditionalPanel("input.tabs == 8",
                                           fluidPage(titlePanel(h4("Wallace was created by an international team of ecologists:")),
                                                     fluidRow(
                                                       column(2, includeMarkdown("www/tab8Acontent.Rmd")),
                                                       column(3, includeMarkdown("www/tab8Ccontent.Rmd")),
                                                       column(5, includeMarkdown("www/tab8Bcontent.Rmd"))
                                                     )
                                           )
                          )
                        )
))
