install.packages('Rcpp')
install.packages('shiny')
install.packages('shinyjs')
install.packages('munsell')
install.packages('DBI')
install.packages('spocc')
install.packages('backports')
install.packages('rmarkdown')
install.packages('spThin')
install.packages('ENMeval')
install.packages('repmis')

install.packages('devtools')
devtools::install_github('wallaceEcoMod/wallace')
# install_github('bobmuscarella/ENMeval@ENMeval_v0.1.2')