install.packages('Rcpp')
install.packages('shiny')
install.packages('shinyjs')
install.packages('munsell')
install.packages('DBI')
install.packages('spocc')
install.packages('backports')
install.packages('rmarkdown')
install.packages('spThin')
install.packages('repmis')
install.packages('xtable')
install.packages('gtable')

install.packages('devtools')
devtools::install_github('bobmuscarella/ENMeval@Edits_on_v0.2.1')
