---
title: "comp1_userOccs"
output: html_document
---

### **Module:** ***User-specified Ocurrences*** 

**BACKGROUND**  

A user can upload data documenting the presence of a species at particular points in space and time, along with assigned georeferences (i.e., latitude/longitude coordinates). Other useful metadata fields when available (e.g., institution, specimen/observation number, elevation, etc.). 

**IMPLEMENTATION** 
The user may upload a .csv file of occurrence records to use in the analysis, such as processed versions of files previously downloaded via *Wallace*. Such a file must contain rows of localities, and the first three columns should be “species”, “longitude”, and “latitude” (in that order, with those names).  


The R package `spocc` provides *streamlined* access to many species occurrence databases, some of which aggregate data from myriad providers. In Module ***Query Database*** users can choose between three of the largest databases: <a href="http://www.gbif.org" target="_blank">GBIF</a>, <a href="http://www.vertnet.org" target="_blank">VertNet</a>, and <a href="https://bison.usgs.gov" target="_blank">BISON</a>. The resulting table includes several key fields: JAMIE LIST THEM. The records downloaded are restricted to those with georeferences. The table displays all such records (and allows their download), but records with exact duplicate coordinates are removed for visualizaion and use in downstream components of *Wallace*. Users can download a .csv file with all the original fields provided.
