---
title: "tab8_pjArea"
output: html_document
---

### **Module:** ***Project to New Extent***

**BACKGROUND**  

In simple terms, applying or “projecting” a niche/distributional model to a time period or region different from the study extent constitutes a simple model prediction on the predictor values, as long as these values are available for the new projection extent / time. In reality, however, researchers should be cognizant of many possible pitfalls, including non-analog conditions (e.g., requiring extrapolation in environmental space), dispersal barriers, and heterogeneity in the effects of biotic interactors (Anderson 2013).

**IMPLEMENTATION** 

Users begin by selecting a model. In the case of BIOCLIM, there is only one choice, whereas depending on the `ENMeval` settings set in Component **Model**, there may be many choices for Maxent. Users then draw a polygon on the map to delineate the model prediction area. Once the polygon has been drawn, users can press "Select" to choose this extent, and then "Project" to project the model onto the predictor values of the selected extent.

**REFERENCES**

Anderson R.P. 2013. A framework for using niche models to estimate impacts of climate change on species distributions. *Annals of the New York Academy of Sciences*. 1297:8–28.
