---
title: "comp6_maxent"
output: html_document
---

### **Module:** ***Maxent***

**BACKGROUND**

Maxent is a machine learning algorithm that estimates the species response to the environment while constraining this response to be as close to the background environment as possible (Elith et al. 2011). The background environment is defined by a random point sample over the study extent. Thus, Maxent is called a presence-background ENM technique, as it compares species occurrences with background points. It has been shown to be among the most accurate ENM techiques for a wide range of environments and species (Elith et al. 2006), even for small sample sizes (Hernandez et al. 2006).

A hallmark of many machine learning techniques are internal decisions about variable selection and model fit. Maxent allows users to modify two key parameters to control model complexity: feature classes and the regularization multiplier. Feature classes allow more flexible model fits, and thus more feature classes means more potential model complexity. Increasing the regularization multiplier penalizes complexity by increasingly shrinking the effect of each variable to 0 -- those remaining are considered important to model the response and are retained. These settings can hold especially strong influence on model output, and this sensitivity is well documented for Maxent (Warren and Seifert 2011, Radosavljevic & Anderson 2014). For these reasons, evaluating model quality and estimating optimal model complexity constitute important elements of a niche/distributional modeling study with Maxent. More details on these settings and other aspects of Maxent can be found in the literature (Elith et al. 2011, Merow et al. 2013).

**IMPLEMENTATION** 

This module uses the R packages `ENMeval` and `dismo` to build and evaluate Maxent niche/distributional models across a wide range of model settings (Muscarella et al. 2014). It automates two workflows: 1) building a suite of candidate models with differing limitations on complexity; and 2) quantifying their performance. Regarding the first, it makes models with various combinations of feature classes (e.g., linear, quadratic, hinge) and regularization multipliers (higher values provide stronger penalties for parameters included in the model, and hence they tend to lead to simpler models, with fewer variables included in the final model). The field remains far from any consensus regarding model evaluation and estimation of optimal model complexity (especially for presence-background datasets like those used in Maxent). Nevertheless, the evaluation metrics provided here can aid the user in selecting optimal settings (Radosavljevic & Anderson 2014). Users can download the evaluation table as a .csv file.

**REFERENCES**

Elith J., Graham C.H., Anderson R.P., Dudík M., Ferrier S., Guisan A., Hijmans R.J., Huettmann F., Leathwick J.R., Leahmann A., Li J., Lohmann L.G., Loiselle B.A., Manion G., Moritz C., Nakamura M., Nakazawa Y., Overton J.M., Peterson A.T., Phillips S.J., Richardson K.S., Scachetti-Pereira R., Schapire R.E., Soberón J., Williams S., Wisz M.S., Zimmermann N.E. 2006. Novel methods improve prediction of species’ distributions from occurrence data. *Ecography*. 29:129–151.

Hernandez, P. A., Graham, C. H., Master, L. L., & Albert, D. L. (2006). The effect of sample size and species characteristics on performance of different species distribution modeling methods. *Ecography*, 29(5), 773-785.

Merow C., Smith M.J., Silander J.A. 2013. A practical guide to MaxEnt for modeling species’ distributions: What it does, and why inputs and settings matter. *Ecography*. 36:1058–1069.

Muscarella, R., Galante, P. J., Soley‐Guardia, M., Boria, R. A., Kass, J. M., Uriarte, M., & Anderson, R. P. 2014. ENMeval: An R package for conducting spatially independent evaluations and estimating optimal model complexity for Maxent ecological niche models. *Methods in Ecology and Evolution*, 5:1198-1205.

Radosavljevic A., Anderson R.P. 2014. Making better Maxent models of species distributions: complexity, overfitting and evaluation. *Journal of Biogeography*. 41:629–643.

Warren, D. L., & Seifert, S. N. (2011). Ecological niche modeling in Maxent : the importance of model complexity and the performance of model selection criteria. *Ecological Applications*, 21(2), 335–342.
