---
title: "comp3_worldclim"
output: html_document
---

### **Module:** ***WorldClim***

**BACKGROUND**

The WorldClim project provides bioclimatic variables for the Earth’s land surfaces for all continents except Antarctica. Monthly data from weather stations were spatially extrapolated using elevation as a covariate and 19 bioclimatic variables were derived, reflecting various apects of temperature and precipitation (Hijmans et al. 2005). More details can be found at the WorldClim <a href="http://www.worldclim.org" target="_blank">website</a>.

**IMPLEMENTATION**

The Module “WorldClim” relies on the R package `dismo` to download bioclimatic variables from the WorldClim server. *Wallace* makes all four resolutions of the data available (10 arcmin, 5 arcmin, 2.5 arcmin, and 30 arcsec). When running *Wallace* locally, the dataset is downloaded which might take some time, but upon subsequent uses *Wallace* will simply use the files previously downloaded.

**REFERENCES**

Hijmans, R. J., Cameron, S. E., Parra, J. L., Jones, P. G., & Jarvis, A. 2005. Very high resolution interpolated climate surfaces for global land areas. *International Journal of Climatology*. 25:1965-1978.
