---
title: "comp2_spatialThin"
output: html_document
---
**BACKGROUND**
<p align="justify">
In addition to the possibility of errors regarding identification and georeferencing, datasets of occurrence records typically suffer from the effects of uneven (i.e., biased) sampling across geography, such as more effort near roads and established research centers (Reddy and Dávalos 2003). Geographically biased sampling also may yield biases in environmental space (distorting estimates of the species’ niche; Kadmon et al. 2004). Furthermore, it can falsely inflate estimates of model performance (Veloz 2009). Some ways of dealing with this problem include: 1) quantifying heterogeneity in sampling effort across geography (e.g., via the results of sampling for a “target group” of species detected with the same techniques; (Anderson 2003) and correcting for such spatial sampling patterns during model building (Phillips et al. 2009); or 2) reducing the effects of biased sampling via thinning of records based on geographic or environmental distances (Varela et al. 2014).  
</p>
**IMPLEMENTATION**
<p align="justify">
The Module “Spatial Thinning” implements the R package spThin, which removes localities less than a user-specified geographic distance from other localities (Aiello-Lammens et al. 2015). If run with sufficient (independent) repetitions, spThin will produce at least one dataset that retains the maximal number of localities possible while satisfying the constraint of the minimum distance between them. This distance is user-specified and typically is set by expert opinion. Alternatively, it could be determined empirically for a given dataset through experiments that examine various distances and select the one that performs the best in independent evaluations (Boria et al. 2014). As implemented here, spThin is run for 100 repetitions and returns one thinned dataset with the maximum retained number of localities.  
</p>
<p align="justify">
The output of this component is a CSV file with rows of localities, and columns containing species,
longitude, and latitude.
</p>

<p align="justify">
<div style="font-size:9pt;font-weight:bold">References</div><p>
<div style="font-size:9pt;font-style:italic">
Aiello-Lammens M.E., Boria R.A., Radosavljevic A., Vilela B., Anderson R.P. 2015. spThin: an R package for spatial thinning of species occurrence records for use in ecological niche models. Ecography. 38:541–545.<p><br>

Anderson R.P. 2003. Real vs. artefactual absences in species distributions: tests for Oryzomys albigularis (Rodentia: Muridae) in Venezuela. Journal of Biogeography. 30:591–605.<p>

Boria R.A., Olson L.E., Goodman S.M., Anderson R.P. 2014. Spatial filtering to reduce sampling bias can improve the performance of ecological niche models. Ecological Modelling. 275:73–77.<p>

Kadmon R., Farber O., Danin A. 2004. Effect of roadside bias on the accuracy of predictive maps produced by bioclimatic models. Ecological Applications. 14:401–413.<p>

Phillips S.J., Dudík M., Elith J., Graham C.H., Lehmann A., Leathwick J., Ferrier S. 2009. Sample selection bias and presence-only distribution models: implications for background and pseudo-absence data. Ecological Applications. 19:181–197.<p>

Reddy S., Dávalos L.M. 2003. Geographic sampling bias and its implications for conservation priorities in Africa. 30:1719–1727.<p>

Varela S., Anderson R.P., García-Valdés R., Fernández-González F. 2014. Environmental filters reduce the effects of sampling bias and improve predictions of ecological niche models. Ecography. 37:1084–1091.<p>

Veloz S.D. 2009. Spatially autocorrelated sampling falsely inflates measures of accuracy for presence-only niche models. Journal of Biogeography. 36:2290–2299.<p>
</div>
