---
title: "tab4content"
output: html_document
---
**BACKGROUND**
<p align="justify">
For many niche/distribution modeling approaches (including Maxent; see Step 6), selection of a study region is critical because it defines the grid cells (of absence, pseudoabsence, or background information; Anderson 2013): p. 14) whose environmental values are compared with those of the cells that hold occurrence localities of the species. Various principles for selecting a study region have been set forth in the literature. Some emphasize the geographic or environmental domain over which to build the model, whereas others suggest identification of areas where the species is likely to be at environmental equilibrium with the predictor variables (Anderson and Raza 2010; Barve et al. 2011; Anderson 2013).  
</p>
**IMPLEMENTATION** 
<p align="justify">
Module “Select Study Region” provides two simple ways to delimit a study region, or accepts a user-specified polygon. Here, the user can choose either a bounding box or a minimum convex polygon around the localities, as well as a buffer distance. Wallace then clips the environmental grids. This module relies on custom code as well as important functions from the R packages rgeos and sp.  
</p>

<p>
<div style="font-size:9pt;font-weight:bold">References</div><p>
<div style="font-size:9pt;font-style:italic">
Anderson R.P., Raza A. 2010. The effect of the extent of the study region on GIS models of species geographic distributions and estimates of niche evolution: preliminary tests with montane rodents (genus Nephelomys) in Venezuela. Journal of Biogeography. 37:1378–1393.<p><br>

Anderson R.P. 2013. A framework for using niche models to estimate impacts of climate change on species distributions. Annals of the New York Academy of Sciences. 1297:8–28.<p>

Barve N., Barve V., Jiménez-Valverde A., Lira-Noriega A., Maher S.P., Peterson A.T., Soberón J., Villalobos F. 2011. The crucial role of the accessible area in ecological niche modeling and species distribution modeling. Ecological Modelling. 222:1810–1819.<p>
</div>
