source("funcs/functions.R", local = TRUE)
# load modules
for (f in list.files('./modules')) {
  source(file.path('modules', f), local=TRUE)
}

# Define UI for application
shinyUI(tagList(
  shinyjs::useShinyjs(),
  navbarPage(theme=shinythemes::shinytheme('united'), id='tabs', collapsible=TRUE,
             title='Wallace',
             tabPanel("Intro", value=0),
             tabPanel("1 Occ Data", value=1),
             tabPanel("2 Process Occs", value=2),
             tabPanel("3 Env Data", value=3),
             tabPanel("4 Process Envs", value=4),
             tabPanel("5 Partition Occs", value=5),
             tabPanel("6 Model", value=6),
             tabPanel("7 Visualize", value=7),
             # tabPanel("8 Project", value=8),
             tabPanel("Session Code", value='rmd'),
             
             fluidRow(column(4,
                             wellPanel(
                               includeCSS(system.file("css", "styles.css", package = "wallace")),
                               includeScript(system.file("js", "scroll.js", package = "wallace")),
                               conditionalPanel("input.tabs == 0",
                                                actionButton('load', 'HACK'),
                                                includeMarkdown(system.file("Rmd", "text_intro_tab.Rmd", package = "wallace"))
                               ),
                               # tab 1 ####
                               conditionalPanel("input.tabs == 1",
                                                h4("Obtain Occurrence Data"),
                                                radioButtons("occSel", "Modules Available:",
                                                             choices = list("Query Database" = 'db', "User-specified Occurrences" = 'user'),
                                                             selected = 'db'),
                                                HTML('<hr>'),
                                                conditionalPanel("input.occSel == 'db'",
                                                                 div(paste('Module: Query Database'), id="mod"),
                                                                 uiTop('spocc', 'Interface to Species Occurrence Data Sources'),
                                                                 HTML('<hr>'),
                                                                 queryDB_UI('c1_queryDB'),
                                                                 actionButton("goDbOccs", "Query Database"), br(), br(),
                                                                 strong("Download database occurrence localities (.csv)"), br(), br(),
                                                                 downloadButton('dlDbOccs', "Download DB Occurrences"),
                                                                 HTML('<hr>'),
                                                                 uiBottom('spocc', "Scott Chamberlain, Karthik Ram, Ted Hart")
                                                ),
                                                conditionalPanel("input.occSel == 'user'",
                                                                 div('Module: User-specified Occurrences', id="mod"),
                                                                 HTML('<hr>'),
                                                                 userOccs_UI('c1_userOccs'),
                                                                 actionButton("goUserOccs", "Load Occurrences")
                                                )
                               ),
                               # tab 2 ####
                               conditionalPanel("input.tabs == 2",
                                                h4("Process Occurrence Data"),
                                                radioButtons("procOccSel", "Modules Available:",
                                                             choices = list("Select Localities" = 'selpts',
                                                                            "Spatial Thin" = 'spthin')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.procOccSel == 'selpts'",
                                                                 div('Module: Select with Polygon', id="mod"),
                                                                 uiTop('leaflet.extras', "Extra functionality for 'leaflet' Package"),
                                                                 span('package: Create Interactive Web Maps with the JavaScript \'Leaflet\'', id="pkgDes"),
                                                                 HTML('<hr>'),
                                                                 removeByID_UI('c2_removeByID'),
                                                                 actionButton("goRemoveByID", "Remove Occurrence"),
                                                                 HTML('<hr>'),
                                                                 strong("Select localities on map that overlap with polygon"), br(),
                                                                 "* NOTE: draw polygon by clicking on map", br(), br(),
                                                                 actionButton("selectPoly", "Select Localities"), br(), br(),
                                                                 strong("Reset to original localities and erase polygon"), br(), br(),
                                                                 uiBottom('leaflet.extras', 'Bhaskar Karambelkar, Bangyou Zheng')
                                                ),
                                                # placeholder for select on map
                                                conditionalPanel("input.procOccSel == 'spthin'",
                                                                 div(paste('Module: Spatial Thin'), id="mod"),
                                                                 uiTop('spThin', 'Spatial Thinning of Species Occurrence Records'),
                                                                 HTML('<hr>'),
                                                                 thinOccs_UI('c2_thinOccs'),
                                                                 actionButton("goThinOccs", "Thin Occurrences"), br(), br(),
                                                                 HTML('<hr>'),
                                                                 uiBottom('spThin', "Matthew E. Aiello-Lammens, Rob A. Boria, 
                                                                                          Alex Radosavljevic, Bruno Vilela, Robert P. Anderson"),
                                                                 " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/ecog.01132/abstract", target = "_blank")
                                                ),
                                                actionButton("erasePolySelLocs", "Reset"),
                                                HTML('<hr>'),
                                                strong("Download processed occurrence localities (.csv)"), br(), br(),
                                                downloadButton('dlProcOccs', "Download")
                               ),
                               # tab 3 ####
                               conditionalPanel("input.tabs == 3",
                                                h4("Obtain Environmental Data"),
                                                radioButtons("envDataSel", "Modules Available:",
                                                             choices = list("WorldClim Bioclims" = 'wcbc',
                                                                            "User" = 'user')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.envDataSel == 'wcbc'",
                                                                 div(paste('Module: WorldClim Bioclims'), id="mod"),
                                                                 uiTop('raster', 'Geographic Data Analysis and Modeling'),
                                                                 HTML('<hr>'),
                                                                 wcBioclims_UI("c3_wcBioclims"),
                                                                 strong("Using map center coordinates as reference for tile download."),
                                                                 textOutput('ctrLatLon'), br(),
                                                                 actionButton("goEnvData", "Load Env Data")
                                                ),
                                                conditionalPanel("input.envDataSel == 'user'",
                                                                 div('Module: User-specified Environmental Predictors', id="mod"),
                                                                 HTML('<hr>'),
                                                                 userEnvs_UI('c3_userEnvs'),
                                                                 actionButton('goUserEnvs', 'Load Env Data')
                                                ),
                                                # br(), br(),
                                                # strong("Download environmental predictors"), br(), br(),
                                                # downloadButton('dlEnvs', "Download"),
                                                HTML('<hr>'),
                                                uiBottom('raster', "Robert J. Hijmans, Jacob van Etten, Joe Cheng, Matteo Mattiuzzu, 
                                                         Michael Sumner, Jonathan A. Greenberg, Oscar Perpinan Lamigueriro, Andrew Bevan, 
                                                         Etienne B. Racine, Ashton Shortridge"),
                                                " | ", a("WorldClim", href="http://worldclim.org", target="_blank")
                                                
                               ),
                               # tab 4 ####
                               conditionalPanel("input.tabs == 4",
                                                h4("Process Environmental Data"),
                                                radioButtons("envProcSel", "Modules Available:",
                                                             choices = list("Select Study Region" = "bgSel",
                                                                            "User-specified Study Region" = "bgUser")),
                                                
                                                HTML('<hr>'),
                                                conditionalPanel("input.envProcSel == 'bgSel'",
                                                                 div(paste('Module: Select Study Region'), id="mod"),
                                                                 uiTop('sp', 'Title Classes and Methods for Spatial Data'),
                                                                 uiTop('rgeos', 'Interface to Geometry Engine - Open Source (GEOS)'),
                                                                 HTML('<hr>'),
                                                                 bgExtent_UI('c4_bgExtent'),
                                                                 actionButton("goBgExt", "Choose")),
                                                conditionalPanel("input.envProcSel == 'bgUser'",
                                                                 div(paste('Module: User-specified Study Region'), id="mod"),
                                                                 userBgExtent_UI('c4_userBgExtent'),
                                                                 actionButton("goUserBg", "Load")),
                                                conditionalPanel("input.envProcSel == 'bgSel' | input.envProcSel == 'bgUser'",
                                                                 HTML('<hr>'),
                                                                 strong('Mask environmental predictor rasters by polygon'), br(), br(),
                                                                 bgMskAndSamplePts_UI('c4_bgMskAndSamplePts'),
                                                                 actionButton("goBgMask", "Run"), br(), br(),
                                                                 selectInput('bgMskFileType', label = "Select File Type",
                                                                             choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff')),
                                                                 strong("Download masked environmental predictors"), br(), br(),
                                                                 downloadButton('dlMskEnvs', "Download"),
                                                                 HTML('<hr>'),
                                                                 uiBottom('sp', "Edzer Pebesma, Roger Bivand, Barry Rowlingson, Virgilio Gomez-Rubio,
                                                                          Robert Hijmans, Michael Sumner, Don MacQueen, Jim Lemon, Josh O\'Brien"), br(),
                                                                 uiBottom('rgeos', "Roger Bivand, Colin Rundel, Edzer Pebesma, Karl Ove Hufthammer"))
                                                
                               ),
                               conditionalPanel("input.tabs == 5",
                                                h4("Partition Occurrence Data"),
                                                radioButtons("partSel", "Modules Available:",
                                                             choices = list("Non-spatial Partition" = 'nsp',
                                                                            "Spatial Partition" = 'sp')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.partSel == 'sp'",
                                                                 div('Module: Spatial Partition', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 HTML('<hr>'),
                                                                 partSp_UI('c5_partSp'),
                                                                 actionButton("goPartSp", "Partition")),
                                                conditionalPanel("input.partSel == 'nsp'",
                                                                 div('Module: Non-spatial Partition', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 HTML('<hr>'),
                                                                 partNsp_UI('c5_partNsp'),
                                                                 actionButton("goPartNsp", "Partition")),
                                                
                                                strong("Download occurrence and background localities with partition values (.csv)"), br(), br(),
                                                downloadButton('dlPart', "Download"),
                                                HTML('<hr>'),
                                                uiBottom('ENMeval', 'Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                                           Jamie M. Kass, Maria Uriarte, Robert P. Anderson'),
                                                " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank")
                               ),
                               conditionalPanel("input.tabs == 6",
                                                h4("Build and Evaluate Niche Model"),
                                                radioButtons("enmSel", "Modules Available:",
                                                             choices = list("BIOCLIM", "Maxent")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.enmSel == 'Maxent'",
                                                                 div('Module: Maxent', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 uiTop('dismo', 'Species Distribution Modeling'),
                                                                 HTML('<hr>'),
                                                                 htmlOutput('maxentJar'),
                                                                 HTML('<hr>'),
                                                                 maxent_UI('c6_maxent'),
                                                                 actionButton('goMaxent', 'Run')),
                                                conditionalPanel("input.enmSel == 'BIOCLIM'",
                                                                 div('Module: BIOCLIM', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 uiTop('dismo', 'Species Distribution Modeling'),
                                                                 HTML('<hr>'),
                                                                 bioclim_UI('c6_bioclim'),
                                                                 actionButton('goBioclim', 'Run')),
                                                HTML('<hr>'),
                                                uiBottom('ENMeval', 'Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                         Jamie M. Kass, Maria Uriarte, Robert P. Anderson'),
                                                " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank"),
                                                uiBottom('dismo', 'Robert J. Hijmans, Steven Phillips, John Leathwick, Jane Elith')
                               ),
                               conditionalPanel("input.tabs == 7", 
                                                h4("Visualize Model Results"),
                                                radioButtons("visSel", "Modules Available:",
                                                             choices = list("BIOCLIM Envelope Plots" = 'bcEnvel',
                                                                            "Maxent Evaluation Plots" = 'mxEval',
                                                                            "Plot Response Curves" = 'response',
                                                                            "Map Prediction" = 'map')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.visSel == 'bcEnvel'",
                                                                 div('Module: BIOCLIM Envelope Plots', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 uiTop('dismo', 'Species Distribution Modeling'),
                                                                 HTML('<hr>'),
                                                                 bcPlots_UI('c7_bcPlots')),
                                                conditionalPanel("input.visSel == 'mxEval'",
                                                                 div('Module: Maxent Evaluation Plots', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 uiTop('dismo', 'Species Distribution Modeling'),
                                                                 HTML('<hr>'),
                                                                 mxEvalPlots_UI('c7_mxEvalPlots')),
                                                conditionalPanel("input.visSel == 'response'",
                                                                 div('Module: Response Curves', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 uiTop('dismo', 'Species Distribution Modeling'),
                                                                 HTML('<hr>'),
                                                                 respPlots_UI('c7_respPlots')),
                                                conditionalPanel("input.visSel == 'map'",
                                                                 div('Module: Map Prediction', id="mod"),
                                                                 uiTop('ENMeval', 'Automated Runs and Evaluations of Ecological Niche Models'),
                                                                 uiTop('dismo', 'Species Distribution Modeling'),
                                                                 HTML('<hr>'),
                                                                 mapPreds_UI('c7_mapPreds'),
                                                                 actionButton("goMapPreds", "Plot"), br(), br(),
                                                                 selectInput('predFileType', label = "Select File Type",
                                                                             choices = list("GRD" = 'raster', "ASCII" = 'ascii', 
                                                                                            "GeoTIFF" = 'GTiff', "PNG" = "png")),
                                                                 strong("Download displayed raster"), br(), br(),
                                                                 downloadButton('dlPreds', "Download")),
                                                HTML('<hr>'),
                                                uiBottom('ENMeval', 'Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia, Robert A. Boria,
                                                         Jamie M. Kass, Maria Uriarte, Robert P. Anderson'),
                                                " | ", a("software note", href="http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12261/abstract", target = "_blank"),
                                                uiBottom('dismo', 'Robert J. Hijmans, Steven Phillips, John Leathwick, Jane Elith')
                             )
             )),
             column(8,
                    conditionalPanel("input.tabs != 0 & input.tabs != 'rmd'",
                                     div(id = "wallaceLog", class = "scrollbox", htmlOutput("log")),
                                     absolutePanel(top = -10, right = 20, width = 150, draggable = TRUE,
                                                   selectInput("bmap", "Change Base Map", 
                                                               choices = c('ESRI Topo'="Esri.WorldTopoMap",
                                                                           'Stamen Terrain'="Stamen.Terrain",
                                                                           'Open Topo'="OpenTopoMap",
                                                                           'ESRI Imagery'="Esri.WorldImagery",
                                                                           'ESRI Nat Geo'='Esri.NatGeoWorldMap'),
                                                               selected = "Esri.WorldTopoMap")),
                                     absolutePanel(top = 60, right = 20, width = 150, draggable = TRUE,
                                                   uiOutput("modSelUI")),
                                     absolutePanel(top = 60, right = 180, width = 150, draggable = TRUE,
                                                   uiOutput("envSelUI"))
                    ),
                    br(),
                    conditionalPanel("input.tabs != 'rmd' & input.tabs != 0",
                                     tabsetPanel(id = 'main',
                                                 tabPanel('Map', leaflet::leafletOutput("map", height=600)),
                                                 tabPanel('Occs Tbl', DT::dataTableOutput('occTbl')),
                                                 tabPanel('Results', 
                                                          conditionalPanel("input.tabs == 3", verbatimTextOutput('envsPrint')),
                                                          conditionalPanel("input.tabs == 6", DT::dataTableOutput('evalTbl')),
                                                          conditionalPanel("input.tabs == 7 && input.visSel == 'response'",
                                                                           imageOutput('respPlots')),
                                                          conditionalPanel("input.tabs == 7 && input.visSel == 'bcEnvel' && input.enmSel == 'BIOCLIM'",
                                                                           imageOutput('bcEnvelPlot')),
                                                          conditionalPanel("input.tabs == 7 && input.visSel == 'mxEval'  && input.enmSel == 'Maxent'",
                                                                           imageOutput('mxEvalPlots'))
                                                 ),
                                                 tabPanel('Component Guidance', uiOutput('gtext_comp')),
                                                 tabPanel('Module Guidance', uiOutput('gtext_mod'))
                                     )
                    ),
                    conditionalPanel("input.tabs == 'rmd'",
                                     column(8,
                                            includeMarkdown(system.file("Rmd", "text_sessionCode.Rmd", package = "wallace"))
                                     )
                    ),
                    conditionalPanel("input.tabs == 0",
                                     tabsetPanel(id = 'introTabs',
                                                 tabPanel('Intro', includeMarkdown(system.file("Rmd", "text_intro.Rmd", package = "wallace"))),
                                                 tabPanel('About',
                                                          fluidRow(
                                                            column(8, includeMarkdown(system.file("Rmd", "text_about.Rmd", package = "wallace"))
                                                            )
                                                          )
                                                 )
                                     )
                    )
             )
             )
  )
))
