source("funcs/functions.R", local = TRUE)
# load modules
for (f in list.files('./modules')) {
  source(file.path('modules', f), local=TRUE)
}

# Define UI for application
shinyUI(tagList(
  shinyjs::useShinyjs(),
  navbarPage(theme=shinythemes::shinytheme('united'), id='tabs', collapsible=TRUE,
             title='Wallace',
             tabPanel("Intro", value='intro'),
             tabPanel("Occ Data", value='occs'),
             tabPanel("Process Occs", value='poccs'),
             tabPanel("Env Data", value='envs'),
             tabPanel("Process Envs", value='penvs'),
             tabPanel("Env Space", value='espace'),
             tabPanel("Partition Occs", value='part'),
             tabPanel("Model", value='model'),
             tabPanel("Visualize", value='vis'),
             tabPanel("Project", value='proj'),
             tabPanel("Session Code", value='rmd'),
             
             fluidRow(column(4,
                             wellPanel(
                               includeCSS("css/styles.css"),
                               includeScript("js/scroll.js"),
                               conditionalPanel("input.tabs == 'intro'",
                                                actionButton('load', 'HACK'),
                                                includeMarkdown("Rmd/text_intro_tab.Rmd")
                               ),
                               # COMPONENT 1 ####
                               conditionalPanel("input.tabs == 'occs'",
                                                h4("Obtain Occurrence Data"),
                                                radioButtons("occsSel", "Modules Available:",
                                                             choices = list("Query Database (Present)" = 'db', 
                                                                            "Query Database (Paleo)" = 'pdb', 
                                                                            "User-specified" = 'user'),
                                                             selected = 'db'),
                                                HTML('<hr>'),
                                                conditionalPanel("input.occsSel == 'db'",
                                                                 uiTop2(queryDb_INFO),
                                                                 queryDb_UI('c1_queryDb_uiID'),
                                                                 actionButton("goDbOccs", "Query Database"), br(), br(),
                                                                 HTML('<hr>')),
                                                conditionalPanel("input.occsSel == 'pdb'",
                                                                 uiTop2(queryPaleoDb_INFO),
                                                                 queryPaleoDb_UI('c1_queryPaleoDb_uiID'),
                                                                 actionButton("goPaleoDbOccs", "Query Database"), br(), br(),
                                                                 HTML('<hr>')),
                                                conditionalPanel("input.occsSel == 'user'",
                                                                 uiTop2(userOccs_INFO),
                                                                 userOccs_UI('c1_userOccs_uiID'),
                                                                 actionButton("goUserOccs", "Load Occurrences"),
                                                                 HTML('<hr>')),
                                                conditionalPanel("input.occsSel == 'db' | input.occsSel == 'pdb'",
                                                                 strong("Download raw occurrence data"), br(), br(),
                                                                 downloadButton('dlDbOccs', "Download CSV"),
                                                                 HTML('<hr>')),
                                                conditionalPanel("input.occsSel == 'db'", uiBottom2(queryDb_INFO)),
                                                conditionalPanel("input.occsSel == 'pdb'", uiBottom2(queryPaleoDb_INFO)),
                                                conditionalPanel("input.occsSel == 'user'", uiBottom2(userOccs_INFO))
                               ),
                               # COMPONENT 2 ####
                               conditionalPanel("input.tabs == 'poccs'",
                                                h4("Process Occurrence Data"),
                                                radioButtons("procOccsSel", "Modules Available:",
                                                             choices = list("Select Occurrences On Map" = 'selOccs',
                                                                            "Remove Occurrences By ID" = 'remID',
                                                                            "Spatial Thin" = 'spthin')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.procOccsSel == 'selOccs'",
                                                                 uiTop2(selectOccs_INFO),
                                                                 selectOccs_UI('c2_selectOccs_uiID'),
                                                                 strong("Select occurrences intersecting drawn polygon"), br(),
                                                                 "(", HTML("<font color='blue'><b>NOTE</b></font>"), 
                                                                 ': to begin drawing, click hexagon icon on map toolbar, 
                                                                 and when complete, press "Finish" and then the "Select Occurrences" button)', br(), br(),
                                                                 actionButton("goSelectOccs", "Select Occurrences")
                                                ),
                                                conditionalPanel("input.procOccsSel == 'remID'",
                                                                 uiTop2(removeByID_INFO),
                                                                 removeByID_UI('c2_removeByID_uiID'),
                                                                 actionButton("goRemoveByID", "Remove Occurrence")
                                                ),
                                                # placeholder for select on map
                                                conditionalPanel("input.procOccsSel == 'spthin'",
                                                                 uiTop2(thinOccs_INFO),
                                                                 thinOccs_UI('c2_thinOccs_uiID'),
                                                                 actionButton("goThinOccs", "Thin Occurrences")
                                                ), br(),
                                                strong("Reset to original occurrences"), br(), br(),
                                                actionButton("goResetOccs", "Reset"),
                                                HTML('<hr>'),
                                                conditionalPanel("input.procOccsSel == 'selOccs'", uiBottom2(selectOccs_INFO)),
                                                conditionalPanel("input.procOccsSel == 'remID'", uiBottom2(removeByID_INFO)),
                                                conditionalPanel("input.procOccsSel == 'spthin'", uiBottom2(thinOccs_INFO))
                               ),
                               # COMPONENT 3 ####
                               conditionalPanel("input.tabs == 'envs'",
                                                h4("Obtain Environmental Data"),
                                                radioButtons("envsSel", "Modules Available:",
                                                             choices = list("WorldClim Bioclims" = 'wcbc',
                                                                            "ecoClimate"= 'ecoClimate',
                                                                            "User-specified" = 'user')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.envsSel == 'wcbc'",
                                                                 uiTop2(worldclim_INFO),
                                                                 wcBioclims_UI("c3_wcBioclims_uiID"),
                                                                 strong("Using map center coordinates as reference for tile download."),
                                                                 textOutput('ctrLatLon'), br(),
                                                                 actionButton("goEnvData", "Load Env Data")
                                                ),
                                                conditionalPanel("input.envsSel == 'ecoClimatelayers'",
                                                                 uiTop2(ecoclimate_INFO),
                                                                 ecoClimate_UI("c3_ecoClimate_uiID"),
                                                                 strong("ecoClimate layers have a resolution of 0.5 degrees"),
                                                                 actionButton("goEcoClimData", "Load Env Data")
                                                ),
                                                conditionalPanel("input.envsSel == 'user'",
                                                                 uiTop2(userEnvs_INFO),
                                                                 userEnvs_UI('c3_userEnvs_uiID'),
                                                                 actionButton('goUserEnvs', 'Load Env Data')
                                                ),
                                                # br(), br(),
                                                # strong("Download environmental predictors"), br(), br(),
                                                # downloadButton('dlEnvs', "Download"),
                                                HTML('<hr>'),
                                                conditionalPanel("input.envsSel == 'wcbc'", uiBottom2(worldclim_INFO)),
                                                conditionalPanel("input.envsSel == 'ecoClimatelayers'", uiBottom2(ecoclimate_INFO)),
                                                conditionalPanel("input.envsSel == 'user'", uiBottom2(userEnvs_INFO))
                               ),
                               # COMPONENT 4 ####
                               conditionalPanel("input.tabs == 'penvs'",
                                                h4("Process Environmental Data"),
                                                radioButtons("procEnvsSel", "Modules Available:",
                                                             choices = list("Select Study Region" = "bgSel",
                                                                            "User-specified" = "bgUser")),
                                                
                                                HTML('<hr>'),
                                                conditionalPanel("input.procEnvsSel == 'bgSel'",
                                                                 uiTop2(bgExtent_INFO),
                                                                 div("Step 1:", id="step"), div("Choose Background Extent", id="stepText"), br(), br(),
                                                                 bgExtent_UI('c4_bgExtent_uiID'),
                                                                 actionButton("goBgExt", "Select"), br(), br(),
                                                                 strong("Download shapefile of background extent"), br(), br(),
                                                                 downloadButton('dlBgShp', "Download")),
                                                conditionalPanel("input.procEnvsSel == 'bgUser'",
                                                                 uiTop2(userBgExtent_INFO),
                                                                 div("Step 1:", id="step"), div("Choose Background Extent", id="stepText"), br(), br(),
                                                                 userBgExtent_UI('c4_userBgExtent'),
                                                                 actionButton("goUserBg", "Load")),
                                                conditionalPanel("input.procEnvsSel == 'bgSel' | input.procEnvsSel == 'bgUser'",
                                                                 HTML('<hr>'),
                                                                 div("Step 2:", id="step"), div("Sample Background Points", id="stepText"), br(), br(),
                                                                 strong('Mask predictor rasters by background extent and sample background points'), br(), br(),
                                                                 bgMskAndSamplePts_UI('c4_bgMskAndSamplePts'),
                                                                 actionButton("goBgMask", "Sample"), br(), br(),
                                                                 HTML('<hr>'),
                                                                 selectInput('bgMskFileType', label = "Select download file type",
                                                                             choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff')),
                                                                 strong("Download predictor rasters masked to background extent"), br(), br(),
                                                                 downloadButton('dlMskEnvs', "Download")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.procEnvsSel == 'bgSel'", uiBottom2(bgExtent_INFO)),
                                                conditionalPanel("input.procEnvsSel == 'bgUser'", uiBottom2(userBgExtent_INFO))
                               ),
                               # COMPONENT ESPACE ####
                               conditionalPanel("input.tabs == 'espace'",
                                                h4("Environmental Space"),
                                                radioButtons("espaceSel", "Modules Available:",
                                                             choices = list("Principal Components Analysis" = "pca",
                                                                            "Occurrence Density Grid" = "occDens",
                                                                            "Niche Overlap" = "nicheOv")),
                                                
                                                HTML('<hr>'),
                                                conditionalPanel("input.espaceSel == 'pca'",
                                                                 uiTop2(espace_pca_INFO),
                                                                 pca_controlsUI('cEspace_PCA_uiID'),
                                                                 actionButton("goPCA", "Run")
                                                ),
                                                conditionalPanel("input.espaceSel == 'occDens'",
                                                                 uiTop2(espace_occDens_INFO),
                                                                 occDens_controlsUI('cEspace_occDens_uiID'),
                                                                 actionButton("goOccDens", "Run")
                                                ),
                                                conditionalPanel("input.espaceSel == 'nicheOv'",
                                                                 uiTop2(espace_nicheOv_INFO),
                                                                 nicheOv_controlsUI('cEspace_nicheOv_uiID'),
                                                                 actionButton("goNicheOv", "Run")
                                                ),
                                                HTML('<hr>'),
                                                conditionalPanel("input.espaceSel == 'pca'", uiBottom2(espace_pca_INFO)),
                                                conditionalPanel("input.espaceSel == 'occDens'", uiBottom2(espace_occDens_INFO)),
                                                conditionalPanel("input.espaceSel == 'nicheOv'", uiBottom2(espace_nicheOv_INFO))
                               ),
                               # COMPONENT 5 ####
                               conditionalPanel("input.tabs == 'part'",
                                                h4("Partition Occurrence Data"),
                                                radioButtons("partSel", "Modules Available:",
                                                             choices = list("Non-spatial Partition" = 'nsp',
                                                                            "Spatial Partition" = 'sp')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.partSel == 'sp'",
                                                                 uiTop2(partitionSpat_INFO),
                                                                 partSp_UI('cParts_partSp_uiID'),
                                                                 actionButton("goPartSp", "Partition")),
                                                conditionalPanel("input.partSel == 'nsp'",
                                                                 uiTop2(partitionNonSpat_INFO),
                                                                 partNsp_UI('cParts_partNsp_uiID'),
                                                                 actionButton("goPartNsp", "Partition")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.partSel == 'sp'", uiBottom2(partitionSpat_INFO)),
                                                conditionalPanel("input.partSel == 'nsp'", uiBottom2(partitionNonSpat_INFO))
),
                               # COMPONENT 6 ####
                               conditionalPanel("input.tabs == 'model'",
                                                h4("Build and Evaluate Niche Model"),
                                                radioButtons("modelSel", "Modules Available:",
                                                             choices = list("BIOCLIM", "Maxent")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.modelSel == 'Maxent'",
                                                                 uiTop2(maxent_INFO),
                                                                 htmlOutput('maxentJar'), br(),
                                                                 "(", HTML("<font color='blue'><b>NOTE</b></font>"), 
                                                                 ": see module guidance for troubleshooting tips if you are experiencing problems.)",
                                                                 HTML('<hr>'),
                                                                 maxent_UI('c6_maxent'),
                                                                 actionButton('goMaxent', 'Run')),
                                                conditionalPanel("input.modelSel == 'BIOCLIM'",
                                                                 uiTop2(bioclim_INFO),
                                                                 bioclim_UI('c6_bioclim'),
                                                                 actionButton('goBioclim', 'Run')),
                                                HTML('<hr>'),
                                                downloadButton('dlEvalTbl', "Download CSV"),
                                                HTML('<hr>'),
                                                conditionalPanel("input.modelSel == 'Maxent'", uiBottom2(maxent_INFO)),
                                                conditionalPanel("input.modelSel == 'BIOCLIM'", uiBottom2(bioclim_INFO))
                               ),
                               # COMPONENT 7 ####
                               conditionalPanel("input.tabs == 'vis'", 
                                                h4("Visualize Model Results"),
                                                radioButtons("visSel", "Modules Available:",
                                                             choices = list("BIOCLIM Envelope Plots" = 'bioclimPlot',
                                                                            "Maxent Evaluation Plots" = 'maxentEval',
                                                                            "Plot Response Curves" = 'response',
                                                                            "Map Prediction" = 'mapPreds')),
                                                HTML('<hr>'),
                                                conditionalPanel("input.visSel == 'bioclimPlot'",
                                                                 uiTop2(bioclimPlot_INFO),
                                                                 bioclimPlot_UI('c7_bioclimPlot')),
                                                conditionalPanel("input.visSel == 'maxentEval'",
                                                                 uiTop2(maxentEvalPlot_INFO),
                                                                 maxentEvalPlot_UI('c7_maxentEvalPlot')),
                                                conditionalPanel("input.visSel == 'response'",
                                                                 uiTop2(responsePlot_INFO),
                                                                 responsePlot_UI('c7_responsePlot')),
                                                conditionalPanel("input.visSel == 'mapPreds'",
                                                                 conditionalPanel("input.modelSel == 'Maxent'", uiTop2(mapPredsMaxent_INFO)),
                                                                 conditionalPanel("input.modelSel == 'Maxent'", mapPredsMaxent_UI('c7_mapPredsMaxent')), 
                                                                 conditionalPanel("input.modelSel != 'Maxent'", uiTop2(mapPreds_INFO)),
                                                                 conditionalPanel("input.modelSel != 'Maxent'", mapPreds_UI('c7_mapPreds')),
                                                                 actionButton("goMapPreds", "Plot"), br(), br(),
                                                                 HTML('<hr>'),
                                                                 selectInput('predFileType', label = "Select download file type",
                                                                             choices = list("GRD" = 'raster', "ASCII" = 'ascii', 
                                                                                            "GeoTIFF" = 'GTiff', "PNG" = "png"))
                                                                 ),
                                                conditionalPanel("input.visSel == 'bioclimPlot' | input.visSel == 'maxentEval'", downloadButton('dlVizPlot', "Download Plot")),
                                                HTML('<hr>'),
                                                conditionalPanel("input.visSel == 'bioclimPlot'", uiBottom2(bioclimPlot_INFO)),
                                                conditionalPanel("input.visSel == 'maxentEval'", uiBottom2(maxentEvalPlot_INFO)),
                                                conditionalPanel("input.visSel == 'response'", uiBottom2(responsePlot_INFO)),
                                                conditionalPanel("input.visSel == 'mapPreds'", 
                                                                 conditionalPanel("input.modelSel != 'Maxent'", uiBottom2(mapPreds_INFO)),
                                                                 conditionalPanel("input.modelSel == 'Maxent'", uiBottom2(mapPredsMaxent_INFO)))
                               ),
                               # COMPONENT 8 ####
                               conditionalPanel("input.tabs == 'proj'",
                                                h4("Project Model"),
                                                radioButtons("projSel", "Modules Available:",
                                                             choices = list("Project to New Extent" = 'projArea',
                                                                            "Project to New Time" = 'projTime',
                                                                            "Calculate Environmental Similarity" = 'mess'),
                                                             selected = 'projArea'),
                                                HTML('<hr>'),
                                                conditionalPanel("input.projSel == 'projArea'",
                                                                 uiTop2(projectArea_INFO),
                                                                 strong("Project model to current extent"), br(), br(),
                                                                 actionButton('goProjectArea', "Project"), br(), br(),
                                                                 projectArea_UI('c8_projectArea')),
                                                conditionalPanel("input.projSel == 'projTime'",
                                                                 uiTop2(projectTime_INFO),
                                                                 projectTime_UI('c8_projectTime'),
                                                                 strong("Project model to new time for current extent"), br(), br(),
                                                                 actionButton('goProjectTime', "Project")),
                                                conditionalPanel("input.projSel == 'mess'",
                                                                 uiTop2(envSimilarity_INFO),
                                                                 envSimilarity_UI('c8_envSimilarity'),
                                                                 strong("Calculate MESS for current extent"), br(), br(),
                                                                 actionButton('goEnvSimilarity', "Calculate MESS")),
                                                strong("Reset projection extent"), br(), br(),
                                                actionButton("goResetProj", "Reset"),
                                                HTML('<hr>'),
                                                selectInput('projFileType', label = "Select download file type",
                                                            choices = list("GRD" = 'raster', "ASCII" = 'ascii', "GeoTIFF" = 'GTiff',
                                                                           "PNG" = "png")),
                                                strong("Download displayed raster"), br(), br(),
                                                downloadButton('dlProj', "Download"),
                                                HTML('<hr>'),
                                                conditionalPanel("input.projSel == 'projArea'", uiBottom2(projectArea_INFO)),
                                                conditionalPanel("input.projSel == 'projTime'", uiBottom2(projectTime_INFO)),
                                                conditionalPanel("input.projSel == 'mess'", uiBottom2(envSimilarity_INFO))
                               ),
                               # SESSION CODE ####
                               conditionalPanel("input.tabs == 'rmd'",
                                                h4("Download Session Code"),
                                                HTML('<hr>'),
                                                uiTop('rmarkdown', 'Dynamic Documents for R'),
                                                uiTop('knitr', 'A General-Purpose Package for Dynamic Report Generation in R'),
                                                HTML('<hr>'),
                                                selectInput('rmdFileType', label = "Select download file type",
                                                            choices = list("Rmd", "PDF", "HTML", "Word")),
                                                downloadButton('dlRMD', 'Download Session Code'),
                                                HTML('<hr>'),
                                                downloadButton('dlRMM', 'Download Metadata'),
                                                HTML('<hr>'),
                                                uiBottom("Jamie M. Kass, Bruno Vilela, Robert P. Anderson", 'rmarkdown', 'JJ Allaire, Joe Cheng, Yihui Xie, Jonathan McPherson, 
                                                       Winston Chang, Jeff Allen, Hadley Wickham, Aron Atkins, Rob Hyndman, Ruben Arslan'), br(),
                                                uiBottom(NULL, 'knitr', 'Yihui Xie')
                               )
                             )),
                      # RESULTS WINDOW ####
                      column(8,
                             conditionalPanel("input.tabs != 'intro' & input.tabs != 'rmd'",
                                              fixedRow(column(6, div(id = "wallaceLog", class = "scrollbox", htmlOutput("log"))),
                                                       column(2, checkboxInput("batch", label = h4(strong("Batch")), value = TRUE, width = '200%')),
                                                       column(4, fixedPanel(
                                                         uiOutput("curSpUI"),
                                                         uiOutput("curEnvUI"),
                                                         uiOutput("curModelUI"))
                                                       )
                                              )
                             ),
                             br(),
                             conditionalPanel("input.tabs != 'rmd' & input.tabs != 'intro'",
                                              tabsetPanel(id = 'main',
                                                          tabPanel('Map', leaflet::leafletOutput("map", height=600),
                                                                   absolutePanel(top = 160, right = 20, width = 150, draggable = TRUE,
                                                                                 selectInput("bmap", "", 
                                                                                             choices = c('ESRI Topo'="Esri.WorldTopoMap",
                                                                                                         'Stamen Terrain'="Stamen.Terrain",
                                                                                                         'Open Topo'="OpenTopoMap",
                                                                                                         'ESRI Imagery'="Esri.WorldImagery",
                                                                                                         'ESRI Nat Geo'='Esri.NatGeoWorldMap'),
                                                                                             selected = "Esri.WorldTopoMap"))),
                                                          tabPanel('Occs Tbl', br(), fluidRow(column(width=4, tags$h4("Download occurrence data as .csv")), 
                                                                                              column(width=2, downloadButton('dlOccs', "Download Current")),
                                                                                              column(width=2,downloadButton('dlAllOccs', "Download All")),
                                                                                              column(width=4)
                                                                                              ), 
                                                                   br(), DT::dataTableOutput('occTbl')),
                                                          tabPanel('Results', 
                                                                   conditionalPanel("input.tabs == 'envs'", verbatimTextOutput('envsPrint')),
                                                                   conditionalPanel("input.tabs == 'model'", uiOutput('evalTbls')),
                                                                   conditionalPanel("input.tabs == 'vis' && input.visSel == 'response'",
                                                                                    imageOutput('responsePlot')),
                                                                   conditionalPanel("input.tabs == 'vis' && input.visSel == 'bioclimPlot' && input.modelSel == 'BIOCLIM'",
                                                                                    imageOutput('bioclimPlot')),
                                                                   conditionalPanel("input.tabs == 'vis' && input.visSel == 'maxentEval' && input.modelSel == 'Maxent'",
                                                                                    imageOutput('maxentEvalPlot')),
                                                                   conditionalPanel("input.tabs == 'espace' && input.espaceSel == 'pca'",
                                                                                    pca_resultsUI("cEspace_PCA_uiID")),
                                                                   conditionalPanel("input.tabs == 'espace' && input.espaceSel == 'occDens'",
                                                                                    occDens_resultsUI("cEspace_occDens_uiID")),
                                                                   conditionalPanel("input.tabs == 'espace' && input.espaceSel == 'nicheOv'",
                                                                                    nicheOv_resultsUI("cEspace_nicheOv_uiID"))
                                                          ),
                                                          tabPanel('Component Guidance', uiOutput('gtext_component')),
                                                          tabPanel('Module Guidance', uiOutput('gtext_module'))
                                              )
                             ),
                             conditionalPanel("input.tabs == 'rmd'",
                                              column(8,
                                                     includeMarkdown("Rmd/text_sessionCode.Rmd")
                                              )
                             ),
                             conditionalPanel("input.tabs == 'intro'",
                                              tabsetPanel(id = 'introTabs',
                                                          tabPanel('Intro', includeMarkdown("Rmd/text_intro.Rmd")),
                                                          tabPanel('About',
                                                                   fluidRow(
                                                                     column(8, includeMarkdown("Rmd/text_about.Rmd")
                                                                     )
                                                                   )
                                                          )
                                              )
                             )
                      )
             )
  )
))
