---
title: "intro"
output: html_document
---
**What is “Wallace” and why?**  

Welcome to “Wallace: An R-based Modular Web App to Harness Biodiversity Data for Spatial Modeling (ver. beta0.2).” Wallace is a web application designed to facilitate spatial biodiversity research, currently concentrating on modeling niches and distributions using occurrence datasets and environmental predictor variables. These analyses, often termed ecological niche models, species distribution models, or bioclimatic envelope models, provide an estimate of the species’ response to environmental conditions, as well as a map indicating the areas suitable for it (its potential geographic distribution. This research area has grown tremendously over the past two decades, with applications to many academic disciplines, as well as to pressing environmental issues such as conservation biology, invasive species, zoonotic diseases, and climate-change impacts (Elith and Leathwick 2009; Franklin 2010; Peterson et al. 2011).  

Wallace has a graphical user interface (GUI), but it runs on code from “R”, an open-source statistical computing language. Ecologists and other scientists working on studies of biodiversity and the environment have produced myriad useful “packages” in R that other researchers can use freely and customize (R Core Team 2015). In turn, some of those packages also run external programs written in other computer languages. As a result, R users can perform an amazing variety of spatial, ecological, and evolutionary analyses. Taken together, this innovation and flexibility have revolutionized how biodiversity studies are undertaken, both yielding new tools and providing a “glue” to link various applications into seamless workflows. Recently, the package shiny (Chang et al. 2015) was developed to make web applications based on underlying R code—providing the means for us to create Wallace.  

Wallace is innovative by using shiny to bundle key R packages into a convenient interface for obtaining species occurrence records from the Global Biodiversity Information Facility (GBIF) and using them for niche/distributional modeling analyses. In addition to use as a web app, the Wallace GUI also can be run locally on either a Mac or PC. Overall, our vision is to make R tools for spatial biodiversity research easily available to a large group of users, while providing researchers the means to integrate other R packages into Wallace and incentive for them to develop new R packages that could reach a larger set of users through this program. As a useful first demonstration, Wallace offers opportunities (and guidance) to build state-of-the-art niche/distributional models, including a variety of ways to deal with biased occurrence data. Ultimately, fuller implementation of key R packages in Wallace will provide the user with additional options, but in this release we concentrate on those that are most commonly used in the field.  
 
In Wallace, we provide the structure for customizing a given research project, documenting it, and expanding it in the future. It contains various “modules,” each of which corresponds to a particular step of the analysis. This allows future addition of other modules to provide: 1) alternative functionalities for a given process implemented here; and 2) functionalities for processes not currently considered. At several stages, users can upload their own data and save the results. Additionally, as a key element of scientific reproducibility, Wallace uses the R package rmarkdown to write a file with all of the executed code for a given run, providing both documentation of the analysis and a means for re-running it in R. To allow for display and processing in external software platforms and to promote future expansion, we concentrate on a few standard input and output formats (e.g., CSV for occurrence data and GRD, GEOTIFF, or ASCII for raster grids).  

**Building niche/distribution models with Wallace**  

At each step of Wallace, we provide guidance for the user, both regarding data-related issues and the analyses. Overall, the young fields of biodiversity informatics and niche/distributional modeling exist in states of rapid advancement. Because of this, standard practices for most analyses do not yet exist, and the particular tools used change frequently. Nevertheless, many key issues regarding data quality are clear, and many general guidelines for modeling niches and distributions are established in the scientific literature (Guisan and Zimmermann 2000; Guisan and Thuiller 2005; Franklin 2010; Peterson et al. 2011). Therefore, for each step, we attempt to provide succinct orientation and warnings for the user, laying out important principles (that are likely to remain relevant) and providing references to scientific papers holding further details.  

Wallace currently allows users to harness GBIF data and build niche/distributional models with the techniques BIOCLIM and Maxent. Depending on the goals of the study (and the natural history of the species), the particular input predictor variables and relevant study regions will vary. However, two common data needs remain constant: 1) georeferenced occurrence records of the study species; and 2) raster grids of predictor variables (e.g., climate or land-cover). Here, we concentrate on implementations of BIOCLIM and Maxent (Phillips et al. 2006; Booth et al. 2014). Both use data regarding the species’ presence (i.e., without information on absence or non-detection). Maxent also requires a sample of “background” pixels that characterize the environments available in the study region, but BIOCLIM does not. Although Wallace now models one species at a time, relatively minor modifications would allow for batch processing of multiple species. Later expansion is ripe for inclusion of other techniques for building these kinds of models, as well as approaches for presence–absence modeling and occupancy modeling (which uses repeated samples at the same site). Ultimately, we hope that other researchers will add important additional downstream analyses that use the output of niche/distributional models, such as conservation planning tools and macroecological analyses.  


At present, Wallace includes the following steps and modules, as well as the opportunity to download a commented and executable history of the analyses run in a given session:  

STEP 1: Obtain Occurrence Data
Options: GBIF; user-specified  

STEP 2: Process Occurrence Data
Options: Select Localities; Spatial Thin  

STEP 3: Obtain Environmental Data
Options: WorldClim  

STEP 4: Process Environmental Data
Options: Select Study Region (including user-specified)  

STEP 5: Partition Occurrence Data
Options: Non-spatial Partition; or Spatial Partition  

STEP 6: Build and Evaluate Niche Model
Options: BIOCLIM; Maxent  

STEP 7: Visualize Model Results
Options: Map Prediction  

Download Code History  

About  

We dedicate this software to Alfred Russel Wallace, the co-discoverer of evolution by natural selection and the founder of the field of biogeography.  
