---
title: "intro_tab"
output: html_document
---
Wallace includes the steps and modules below, as well as the opportunity to download a commented and executable history of the analyses run in a given session. In each step, function buttons are color-coded as follows: <span style="color:mediumblue;font-weight:bold">NECESSARY</span> (necessary to do for analysis to proceed), 
<span style="color:deepskyblue;font-weight:bold">OPTIONAL</span> (not necessary, but user may choose to do this).

**STEP 1**: *Obtain Occurrence Data*  
Options: GBIF; user-specified  

**STEP 2:** *Process Occurrence Data*  
Options: Select Localities; Spatial Thin  

**STEP 3:** *Obtain Environmental Data*  
Options: WorldClim  

**STEP 4:** *Process Environmental Data*  
Options: Select Study Region (including user-specified)  

**STEP 5:** *Partition Occurrence Data*  
Options: Non-spatial Partition; or Spatial Partition  

**STEP 6:** *Build and Evaluate Niche Model*  
Options: BIOCLIM; Maxent  

**STEP 7:** *Visualize Model Results*  
Options: Map Prediction  

**Download Code History**  
