---
title: "tab1Acontent"
output: html_document
---
**BACKGROUND**  
<p align="justify">
The first step is to download occurrence data if the researcher does not already have a dataset for the species of interest. We are interested in obtaining data that document the presence of a species at particular points in space and time, along with other useful metadata data fields when available. Over the past two decades, the worldwide biodiversity informatics community has achieved remarkable progress, with many millions of occurrence records now available on the internet aggregated via various portals, including a substantial subset of records with assigned georeferences (e.g., latitude/longitude coordinates). These records include digitized data from natural history museums and herbaria, as well as newer data sources, including citizen-science initiatives leveraging mobile technologies.  
</p>

**IMPLEMENTATION** 
<p align="justify">
In the Module “GBIF”, the user downloads occurrence data from the Global Biodiversity Information Facility (GBIF; http://www.gbif.org/), making use of the R package rgbif. Although myriad data providers feed into GBIF, providing a single outlet for biodiversity occurrence data, future releases of Wallace also could include options to download occurrence records from other national or international databases. In this implementation of rgbif, duplicate records (i.e., with the same latitude/longitude) for the focal species are removed, providing unique localities for downstream analyses.
</p>
<p align="justify">
The user’s query returns a table that displays several key fields.  Furthermore, the output of this module is a CSV file that contains rows of localities, with columns for species, longitude, and latitude, as well as all other fields provided by GBIF (for all records returned by GBIF).
</p>
<p align="justify">
The output of this component is a CSV file with rows of localities, and columns containing species,
longitude, and latitude, as well as any other fields provided by GBIF or the user.
