---
title: "tab3Acontent"
output: html_document
---
<span style="font-size:8pt; font-style:italic;color:gray">Packages used: ggplot2, sp, rgeos</span>  

The user then chooses which environmental variables to use as predictors. These data are in raster form. For this demonstration, WorldClim bioclimatic variables are made available at 3 resolutions. For Maxent and many other niche/distribution modeling approaches, selection of a study region is critical because it defines the pixels whose environmental values are compared with those of the pixels holding occurrence records of the species (Anderson & Raza 2010; Barve et al. 2011). As one way to do so, the user can choose a bounding box or minimum convex polygon around the occurrence records, as well as buffer distance for either.

Future versions will include other sets of environmental variables, as well as allow users to upload their own sets of environmental variables and designate a shapefile indicating a custom study region.

<a href="http://worldclim.org" target="_blank">Worldclim homepage</a>
