---
title: "tab3content"
output: html_document
---
**BACKGROUND**
<p align="justify">
For modeling a species’ environmental requirements, the user must choose which predictor variables to use. These data are typically in the form of raster grids. For models aiming to characterize the species’ requirements and the areas suitable for it (and for transfer across space and time), predictor variables should be plausible environmental determinants of the species’ range limits, or likely correlated with them (Austin 2002; Anderson 2013). The WorldClim project provides bioclimatic variables for the Earth’s land surfaces for all continents except Antarctica. Monthly data from weather stations were spatially extrapolated using elevation as a covariate; then, 19 derived bioclimatic variables were generated, reflecting various apects of temperature and precipitation (Hijmans et al. 2005).  
</p>

**IMPLEMENTATION**
<p align="justify">
The Module “WorldClim” relies on the dismo R package to download environmental variables from the WorldClim website. Currently, these variables are made available at 3 resolutions. The first time a user selects a particular resolution on a given server or local computer, Wallace downloads the 19 variables from www.worldclim.org; upon subsequent uses, it uses the files previously archived. Future versions could include alternative sets of environmental variables. Addition of variables for marine environments or past time periods (for analyses with fossil occurrence records) would be especially useful.  
</p>

<p align="justify">
<div style="font-size:9pt;font-weight:bold">References</div><p>
<div style="font-size:9pt;font-style:italic">
Anderson R.P. 2013. A framework for using niche models to estimate impacts of climate change on species distributions. Annals of the New York Academy of Sciences. 1297:8–28.<p><br>

Austin M.P. 2002. Spatial prediction of species distribution: an interface between ecological theory and statistical modelling. Ecological Modelling. 157:101–118.<p>

Hijmans, R. J., Cameron, S. E., Parra, J. L., Jones, P. G., & Jarvis, A. 2005. Very high resolution interpolated climate surfaces for global land areas. International Journal of Climatology. 25:1965-1978.<p>

</div>
