---
title: "comp7_bcplots"
output: html_document
---

### **Module:** ***BIOCLIM Envelope Plots*** 

**BACKGROUND**  

The algorithm BIOCLIM implements Hutchinson’s *n*-dimensional hypervolume concept of the niche, also termed an environmental envelope (Hutchinson 1957; Booth et al. 2014). The model can be visualized in environmental space via what commonly are termed ‘envelope plots’ that indicate the density of occurrence records (and, hence, prediction strength) for any two predictor variables.

**IMPLEMENTATION** 

The envelope plot can be viewed in the "Results" tab. The axes of the plot represent the ranges of different predictor variables. Users can change these axes to view any combination of predictors -- the numbers correspond to the WorldClim bioclimatic variables. Users can also alter the threshold of the envelope.

**BIBLIOGRAPHY**

Booth T.H., Nix H.A., Busby J.R., Hutchinson M.F. 2014. BIOCLIM: The first species distribution modelling package, its early applications and relevance to most current MaxEnt studies. Diversity and Distributions. 20:1–9.
