---
title: "comp3_worldclim"
output: html_document
---

### **Module:** ***WorldClim***

**BACKGROUND**

The WorldClim project provides bioclimatic variables for the Earth’s land surfaces for all continents except Antarctica. Monthly data from weather stations were spatially extrapolated using elevation as a covariate and subsequently 19 bioclimatic variables were derived, reflecting various aspects of temperature and precipitation (Hijmans et al. 2005). More details can be found at the WorldClim <a href="http://www.worldclim.org" target="_blank">website</a>.

**IMPLEMENTATION**

This module relies on the R package `raster` to download bioclimatic variables from the WorldClim server. 

*Wallace* makes all four resolutions of the data available (10 arcmin ≈ 20 km, 5 arcmin ≈ 10 km, 2.5 arcmin ≈ 5 km, and 30 arcsec ≈ 1 km). The finest grain WorldClim dataset (30 arcsec) can only be downloaded by 30 x 30 degree tiles in the current implementation of `dismo` (1.1-1), and so *Wallace* uses the current center of the map display as the tile reference. This means that analyses with 30 arcsec climatic data using the current version of *Wallace* are restricted to the extent of a single tile. When running locally, the dataset is downloaded to the *Wallace* folder (which can take substantial time), but *Wallace* will use the downloaded data for later runs when the same resolution is selected.

**REFERENCES**

Hijmans, R. J., Cameron, S. E., Parra, J. L., Jones, P. G., & Jarvis, A. 2005. Very high resolution interpolated climate surfaces for global land areas. *International Journal of Climatology*. 25: 1965-1978.
