---
title: "comp2_selectLocs"
output: html_document
---

### **Module:** ***Select Localities***

**BACKGROUND**  

Despite their great utility, aggregated biodiversity occurrence datasets typically contain errors both in identification and in georeferencing. Many, but certainly not all, such errors can be spotted by simple visual inspection of the localities plotted on a map (Gaiji et al. 2013). For example, if a species is known only from high elevation forest, and a few localities from an online database are in a lowland grassland, this suspicious pattern may lead users to exclude these records from the analysis. This module can also be used to narrow the analysis on a regional subset of available records.

**IMPLEMENTATION**

The R package `leaflet` provides map functionality to this module, and the polygon drawing tool was implemented with custom code that leverages `leaflet` functions. Future versions of *Wallace* may use the `leaflet` drawing toolbar, which has not yet been integrated into the R package (as of  November 2016).

This module allows users to select which localities to retain on the map either by specifying the ID of localities to *remove* or drawing a polygon to specify which to *retain*. “Remove Locality” deletes a locality based on record ID from the occurrence dataset used for analysis. Record IDs, along with some other information, can be viewed by clicking on points on the map. 

To select multiple points to retain, users can draw a polygon on the map. "Select with Polygon" chooses localities that fall within (i.e. overlap with) the polygon. Users can then draw other polygons to select other groups of localities. This process can be repeated until all the desired localities are selected. Users are also able to reset the occurrence dataset back to the original localities. Finally, users can download a .csv file of the localities.

**REFERENCES**

Gaiji, S., Chavan, V., Ariño, A. H., Otegui, J., Hobern, D., Sood, R., & Robles, E. (2013). Content assessment of the primary biodiversity data published through GBIF network: status, challenges and potentials. Biodiversity Informatics, 8: 94-172.

