```{asis, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit & !proj_time_threshold_knit & proj_time_worldclim_knit}}}
### Project model
Projecting the model to the same modelling area with no threshold rule. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} using a "{{model_rmd}}" GCM and an RCP of {{rcp_rmd}}.

```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit & !proj_time_threshold_knit & proj_time_worldclim_knit}}}
#Download variables for projecting 
projTimeEnvs_{{spAbr}} <- raster::getData(
  'CMIP5',
  var = "bio",
  res = raster::res(bgMask_{{spAbr}}) * 60,
  rcp = {{rcp_rmd}}/10,
  model = "{{model_rmd}}",
  year = {{year_rmd}})

names(projTimeEnvs_{{spAbr}}) <- paste0('bio', c(paste0('0',1:9), 10:19))
# Select variables for projecting to match variables used for modelling 
projTimeEnvs_{{spAbr}} <- projTimeEnvs_{{spAbr}}[[names(bgMask_{{spAbr}})]]

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = bgExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

```

```{asis, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit &  proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit &    proj_time_worldclim_knit}}}
### Project model
Projecting the model to the same modelling area with a "{{thresholdRule_rmd}}" threshold rule of {{threshold_rmd}}. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} using a "{{model_rmd}}" GCM and an RCP of {{rcp_rmd}}.
```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}}
#Download variables for projecting 
projTimeEnvs_{{spAbr}} <- raster::getData(
  'CMIP5',
  var = "bio",
  res = raster::res(bgMask_{{spAbr}}) * 60,
  rcp = {{rcp_rmd}}/10,
  model = "{{model_rmd}}",
  year = {{year_rmd}})

names(projTimeEnvs_{{spAbr}}) <- paste0('bio', c(paste0('0',1:9), 10:19))
# Select variables for projecting to match variables used for modelling 
projTimeEnvs_{{spAbr}} <- projTimeEnvs_{{spAbr}}[[names(bgMask_{{spAbr}})]]

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = bgExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 
# Add threshold if specified 
proj_time_{{spAbr}} <- proj_time_{{spAbr}} < {{threshold_rmd}}

```

```{asis, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit & !proj_time_threshold_knit & proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user drawn area with no threshold. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} using a "{{model_rmd}}" GCM and an RCP of {{rcp_rmd}}.
```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}}
#Download variables for projecting 
projTimeEnvs_{{spAbr}} <- raster::getData(
  'CMIP5',
  var = "bio",
  res = raster::res(bgMask_{{spAbr}}) * 60,
  rcp = {{rcp_rmd}}/10,
  model = "{{model_rmd}}",
  year = {{year_rmd}})

names(projTimeEnvs_{{spAbr}}) <- paste0('bio', c(paste0('0',1:9), 10:19))
# Select variables for projecting to match variables used for modelling 
projTimeEnvs_{{spAbr}} <- projTimeEnvs_{{spAbr}}[[names(bgMask_{{spAbr}})]]

# Generate the projection area according to the drawn polygon in the GUI
proj_draw_{{spAbr}} <-proj_draw(
  polyPjXY = matrix({{polyPjXY_rmd}},ncol=2,byrow=FALSE),
  polyPjID = {{polyPjID_rmd}},
  drawPjBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_draw_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

```

```{asis, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit & proj_time_threshold_knit & proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user drwan area with a "{{thresholdRule_rmd}}" threshold rule of {{threshold_rmd}}. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} using a "{{model_rmd}}" GCM and an RCP of {{rcp_rmd}}.
```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}}
#Download variables for projecting 
projTimeEnvs_{{spAbr}} <- raster::getData(
  'CMIP5',
  var = "bio",
  res = raster::res(bgMask_{{spAbr}}) * 60,
  rcp = {{rcp_rmd}}/10,
  model = "{{model_rmd}}",
  year = {{year_rmd}})

names(projTimeEnvs_{{spAbr}}) <- paste0('bio', c(paste0('0',1:9), 10:19))
# Select variables for projecting to match variables used for modelling 
projTimeEnvs_{{spAbr}} <- projTimeEnvs_{{spAbr}}[[names(bgMask_{{spAbr}})]]

# Generate the projection area according to the drawn polygon in the GUI
proj_draw_{{spAbr}} <-proj_draw(
  polyPjXY = matrix({{polyPjXY_rmd}},ncol=2,byrow=FALSE),
  polyPjID = {{polyPjID_rmd}},
  drawPjBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_draw_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

# Add threshold if specified 
proj_time_{{spAbr}} <- proj_time_{{spAbr}} < {{threshold_rmd}}

```

```{asis, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, eval = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit & !proj_time_threshold_knit & proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user provided area area with no threshold. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} using a "{{model_rmd}}" GCM and an RCP of {{rcp_rmd}}.
```

```{r, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & proj_time_worldclim_knit}}}

# Download variables for projecting 
projTimeEnvs_{{spAbr}} <- raster::getData(
  'CMIP5',
  var = "bio",
  res = raster::res(bgMask_{{spAbr}}) * 60,
  rcp = {{rcp_rmd}}/10,
  model = "{{model_rmd}}",
  year = {{year_rmd}})

names(projTimeEnvs_{{spAbr}}) <- paste0('bio', c(paste0('0',1:9), 10:19))

# Select variables for projecting to match variables used for modelling 
projTimeEnvs_{{spAbr}} <- projTimeEnvs_{{spAbr}}[[names(bgMask_{{spAbr}})]]

# Generate the projection area based on user provided files
  ##User must input the path to shapefile or csv file and the file name 
proj_userExt_{{spAbr}} <- proj_userExtent(
  bgShp_path = "Input path here",
  bgShp_name = "Input file name here",
  userBgBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_userExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

```

```{asis, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, eval = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit & proj_time_threshold_knit & proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user provided area with a "{{thresholdRule_rmd}}" threshold rule of {{threshold_rmd}}. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} using a "{{model_rmd}}" GCM and an RCP of {{rcp_rmd}}.
```

```{r, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & proj_time_worldclim_knit}}}

# Download variables for projecting from Worldclim
projTimeEnvs_{{spAbr}} <- raster::getData(
  'CMIP5',
  var = "bio",
  res = raster::res(bgMask_{{spAbr}}) * 60,
  rcp = {{rcp_rmd}}/10,
  model = "{{model_rmd}}",
  year = {{year_rmd}})

names(projTimeEnvs_{{spAbr}}) <- paste0('bio', c(paste0('0',1:9), 10:19))

# Select variables for projecting to match variables used for modelling 
projTimeEnvs_{{spAbr}} <- projTimeEnvs_{{spAbr}}[[names(bgMask_{{spAbr}})]]

# Generate the projection area based on user provided files
  ##User must input the path to shapefile or csv file and the file name 
proj_userExt_{{spAbr}} <- proj_userExtent(
  bgShp_path = "Input path here",
  bgShp_name = "Input file name here",
  userBgBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_userExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 
# Add threshold if specified 
proj_time_{{spAbr}} <- proj_time_{{spAbr}} < {{threshold_rmd}}

```


```{asis, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit & !proj_time_threshold_knit & !proj_time_worldclim_knit}}}
### Project model
Projecting the model to the same modelling area with no threshold rule. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} to {{yearMax_rmd}} using a "{{pjAOGCM_rmd}}" GCM and a "{{pjScenario_rmd}}" scenario.
```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit & !proj_time_threshold_knit & !proj_time_worldclim_knit}}}
#Download data from ecoClimate for projecting
projTimeEnvs_{{spAbr}} <- envs_ecoClimate(
  "{{pjAOGCM_rmd}}",
  "{{pjScenario_rmd}}",
  as.numeric(gsub("bio", "", names(envs()))))

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}} ,
  pjExt = bgExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

```

```{asis, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit &  !proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit &    !proj_time_worldclim_knit}}}
### Project model
Projecting the model to the same modelling area with a "{{thresholdRule_rmd}}" threshold rule of {{threshold_rmd}}. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} to {{yearMax_rmd}} using a "{{pjAOGCM_rmd}}" GCM and a "{{pjScenario_rmd}}" scenario.
```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}}
#Download data from ecoClimate for projecting
projTimeEnvs_{{spAbr}} <- envs_ecoClimate(
  "{{pjAOGCM_rmd}}",
  "{{pjScenario_rmd}}",
  as.numeric(gsub("bio", "", names(envs()))))

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}} ,
  pjExt = bgExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 
# Add threshold if specified 
proj_time_{{spAbr}} <- proj_time_{{spAbr}} < {{threshold_rmd}}

```

```{asis, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit & !proj_time_threshold_knit & !proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user drawn area with no threshold rule. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} to {{yearMax_rmd}} using a "{{pjAOGCM_rmd}}" GCM and a "{{pjScenario_rmd}}" scenario.

```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}}
#Download data from ecoClimate for projecting
projTimeEnvs_{{spAbr}} <- envs_ecoClimate(
  "{{pjAOGCM_rmd}}",
  "{{pjScenario_rmd}}",
  as.numeric(gsub("bio", "", names(envs()))))

# Generate the projection area according to the drawn polygon in the GUI
proj_draw_{{spAbr}} <-proj_draw(
  polyPjXY = matrix({{polyPjXY_rmd}},ncol=2,byrow=FALSE),
  polyPjID = {{polyPjID_rmd}},
  drawPjBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_draw_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

```

```{asis, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, eval = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit & proj_time_threshold_knit & !proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user drawn area with a "{{thresholdRule_rmd}}" threshold rule of {{threshold_rmd}}. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} to {{yearMax_rmd}} using a "{{pjAOGCM_rmd}}" GCM and a "{{pjScenario_rmd}}" scenario.

```

```{r, echo = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & !proj_time_user_knit & proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}}
#Download data from ecoClimate for projecting
projTimeEnvs_{{spAbr}} <- envs_ecoClimate(
  "{{pjAOGCM_rmd}}",
  "{{pjScenario_rmd}}",
  as.numeric(gsub("bio", "", names(envs()))))

# Generate the projection area according to the drawn polygon in the GUI
proj_draw_{{spAbr}} <-proj_draw(
  polyPjXY = matrix({{polyPjXY_rmd}},ncol=2,byrow=FALSE),
  polyPjID = {{polyPjID_rmd}},
  drawPjBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_draw_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

# Add threshold if specified 
proj_time_{{spAbr}} <- proj_time_{{spAbr}} < {{threshold_rmd}}

```

```{asis, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, eval = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit & !proj_time_threshold_knit & !proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user provided area with no threshold rule. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} to {{yearMax_rmd}} using a "{{pjAOGCM_rmd}}" GCM and a "{{pjScenario_rmd}}" scenario.
```

```{r, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  !proj_time_threshold_knit & !proj_time_worldclim_knit}}}
#Download data from ecoClimate for projecting
projTimeEnvs_{{spAbr}} <- envs_ecoClimate(
  "{{pjAOGCM_rmd}}",
  "{{pjScenario_rmd}}",
  as.numeric(gsub("bio", "", names(envs()))))

# Generate the projection area based on user provided files
  ##User must input the path to shapefile or csv file and the file name 
proj_userExt_{{spAbr}} <- proj_userExtent(
  bgShp_path = "Input path here",
  bgShp_name = "Input file name here",
  userBgBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_userExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 

```

```{asis, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, eval = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit & proj_time_threshold_knit & !proj_time_worldclim_knit}}}
### Project model
Projecting the model to a user provided area with a "{{thresholdRule_rmd}}" threshold rule of {{threshold_rmd}}. New time based on "{{envs_name_rmd}}" variables for {{yearMin_rmd}} to {{yearMax_rmd}} using a "{{pjAOGCM_rmd}}" GCM and a "{{pjScenario_rmd}}" scenario.
```

```{r, echo = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}, include = {{proj_time_knit & proj_time_user_knit & !proj_time_drawn_knit &  proj_time_threshold_knit & !proj_time_worldclim_knit}}}

#Download data from ecoClimate for projecting
projTimeEnvs_{{spAbr}} <- envs_ecoClimate(
  "{{pjAOGCM_rmd}}",
  "{{pjScenario_rmd}}",
  as.numeric(gsub("bio", "", names(envs()))))

# Generate the projection area based on user provided files
  ##User must input the path to shapefile or csv file and the file name 
proj_userExt_{{spAbr}} <- proj_userExtent(
  bgShp_path = "Input path here",
  bgShp_name = "Input file name here",
  userBgBuf = {{BgBuf_rmd}},
  spN = "{{spName}}")

# Generate a projection of the model to the desired area and time
proj_time_{{spAbr}} <-proj_time(
  evalOut = model_{{spAbr}},
  curModel = "{{curModel_rmd}}",
  envs = projTimeEnvs_{{spAbr}},
  pjExt = proj_userExt_{{spAbr}},
  alg = "{{alg_rmd}}",
  outputType = "{{outputType_rmd}}",
  clamp = {{clamp_rmd}},
  spN = "{{spName}}") 
# Add threshold if specified 
proj_time_{{spAbr}} <- proj_time_{{spAbr}} < {{threshold_rmd}}

```
