```{asis, echo = {{vis_responsePlot_knit & vis_maxnet_knit}}, eval = {{vis_responsePlot_knit & vis_maxnet_knit}}, include = {{vis_responsePlot_knit & vis_maxnet_knit}}}
### Visualize
Visualize response curves from "{{alg_rmd}}" model.
```

```{r, echo = {{vis_responsePlot_knit & vis_maxnet_knit}}, include = {{vis_responsePlot_knit & vis_maxnet_knit}}}
# Create response curves
namesEnvs <- mxNonzeroCoefs(model_{{spAbr}}@models[["{{curModel_rmd}}"]], "maxnet")
  for (i in namesEnvs) {
    maxnet::response.plot(
      model_{{spAbr}}@models[["{{curModel_rmd}}"]],
      v = i,
      type = "cloglog")
  }

```

```{asis, echo = {{vis_responsePlot_knit & !vis_maxnet_knit}}, eval = {{vis_responsePlot_knit & !vis_maxnet_knit}}, include = {{vis_responsePlot_knit & !vis_maxnet_knit}}}
### Visualize
Visualize response curves from "{{alg_rmd}}" model.
```

```{r, echo = {{vis_responsePlot_knit & !vis_maxnet_knit }}, include = {{vis_responsePlot_knit & !vis_maxnet_knit}}}
# Create response curves
namesEnvs <- mxNonzeroCoefs(model_{{spAbr}}@models[["{{curModel_rmd}}"]], "maxent.jar")
for (i in namesEnvs) {
  plot(
    predicts::partialResponse(model_{{spAbr}}@models[["{{curModel_rmd}}"]], var = i),
    type="l")
  }

```
